import {
  OptimizationTweak,
  DriverItem,
  MaintenanceStep,
  GameProfile,
  StartupApp,
  AntiCheatEngine,
  UefiVendorProvider,
  ChangeJournalEntry,
} from '../types';

export const INITIAL_OPTIMIZATION_TWEAKS: OptimizationTweak[] = [
  // --- VERIFIED SAFE TWEAKS ---
  {
    id: 'safe-01',
    title: 'Hardware-Accelerated GPU Scheduling (HAGS)',
    category: 'Gaming & GPU',
    description: 'Offloads high-priority GPU memory management to a dedicated RISC processor on modern GPUs.',
    riskLevel: 'SAFE',
    isApplied: true,
    expectedBenefit: 'Reduces DirectX 12 render latency by 3-8ms and improves frame time consistency.',
    technicalDetails: 'Sets Registry: HKEY_LOCAL_MACHINE\\SYSTEM\\CurrentControlSet\\Control\\GraphicsDrivers\\HwSchMode = 2',
    powershellApply: 'Set-ItemProperty -Path "HKLM:\\SYSTEM\\CurrentControlSet\\Control\\GraphicsDrivers" -Name "HwSchMode" -Value 2',
    powershellRollback: 'Set-ItemProperty -Path "HKLM:\\SYSTEM\\CurrentControlSet\\Control\\GraphicsDrivers" -Name "HwSchMode" -Value 1',
    verifiedBy: 'Windows 11 Hardware Lab',
    antiCheatImpact: 'COMPATIBLE',
  },
  {
    id: 'safe-02',
    title: 'Automated SSD TRIM & Storage Sense Schedule',
    category: 'Storage & SSD',
    description: 'Executes NVMe/SATA garbage collection blocks and automatically purges temporary upgrade caches.',
    riskLevel: 'SAFE',
    isApplied: true,
    expectedBenefit: 'Maintains peak SSD write IOPS and reclaims up to 15GB of stale logs.',
    technicalDetails: 'Runs `Optimize-Volume -DriveLetter C -ReTrim -Verbose` and configures Storage Sense Registry.',
    powershellApply: 'Optimize-Volume -DriveLetter C -Defrag -ReTrim; Set-ItemProperty -Path "HKCU:\\Software\\Microsoft\\Windows\\CurrentVersion\\StorageSense\\Parameters\\StoragePolicy" -Name "01" -Value 1',
    powershellRollback: '# Storage Sense remains optional via Windows Settings UI',
    verifiedBy: 'Rigorset Security Audit',
    antiCheatImpact: 'COMPATIBLE',
  },
  {
    id: 'safe-03',
    title: 'Nagle Algorithm & TCP Latency Optimization',
    category: 'Network',
    description: 'Disables packet queuing delays for real-time multiplayer gaming packets.',
    riskLevel: 'SAFE',
    isApplied: false,
    expectedBenefit: 'Lowers online gaming ping jitter by 4-12ms without degrading throughput.',
    technicalDetails: 'Configures TCPAckFrequency = 1 and TCPNoDelay = 1 under active Network Interface GUID.',
    powershellApply: 'Set-ItemProperty -Path "HKLM:\\SYSTEM\\CurrentControlSet\\Services\\Tcpip\\Parameters\\Interfaces\\*" -Name "TcpAckFrequency" -Value 1',
    powershellRollback: 'Remove-ItemProperty -Path "HKLM:\\SYSTEM\\CurrentControlSet\\Services\\Tcpip\\Parameters\\Interfaces\\*" -Name "TcpAckFrequency"',
    verifiedBy: 'Community Verified',
    antiCheatImpact: 'COMPATIBLE',
  },
  {
    id: 'safe-04',
    title: 'Windows 11 Memory Compression Engine',
    category: 'Memory',
    description: 'Compresses inactive background pages in RAM instead of paging them directly to disk.',
    riskLevel: 'SAFE',
    isApplied: true,
    expectedBenefit: 'Frees up 2-4GB of physical RAM instantly without causing disk thrashing.',
    technicalDetails: 'Executes `Enable-MMAgent -MemoryCompression` in PowerShell.',
    powershellApply: 'Enable-MMAgent -MemoryCompression',
    powershellRollback: 'Disable-MMAgent -MemoryCompression',
    verifiedBy: 'Windows 11 Hardware Lab',
    antiCheatImpact: 'COMPATIBLE',
  },
  {
    id: 'safe-05',
    title: 'Delivery Optimization & Update Cache Cleanup',
    category: 'Privacy & Services',
    description: 'Purges accumulated Microsoft peer-to-peer update distribution files.',
    riskLevel: 'SAFE',
    isApplied: false,
    expectedBenefit: 'Reclaims 3GB - 12GB of drive space and stops background update seeding bandwidth.',
    technicalDetails: 'Clears C:\\Windows\\SoftwareDistribution\\Download and sets DoConfig = 0.',
    powershellApply: 'Stop-Service wuauserv; Remove-Item -Path "C:\\Windows\\SoftwareDistribution\\Download\\*" -Recurse -Force; Start-Service wuauserv',
    powershellRollback: '# Re-enabled automatically when Windows Update runs next',
    verifiedBy: 'Rigorset Security Audit',
    antiCheatImpact: 'COMPATIBLE',
  },

  // --- DISCARDED & RISKY / SNAKE-OIL TWEAKS (EXPLICITLY IDENTIFIED) ---
  {
    id: 'discard-01',
    title: 'EmptyWorkingSet / "RAM Cleaner" Tools',
    category: 'Memory',
    description: 'Aggressively flushes all application working sets directly out of physical RAM.',
    riskLevel: 'DISCARD_SNAKE_OIL',
    isApplied: false,
    expectedBenefit: 'FALSE ILLUSION: Shows temporary low RAM reading in Task Manager.',
    technicalDetails: 'Calls PSAPI `EmptyWorkingSet()` across all process handles indiscriminately.',
    whyDiscardedOrWarning:
      'DISCARDED & BLOCKED BY RIGORSET: Forces Windows 11 to instantly fault all required memory pages back from the SSD, causing severe micro-stutter, high disk IO wear, and sluggish app response.',
    powershellApply: '# BLOCKED: Rigorset explicitly refuses to run EmptyWorkingSet wrappers.',
    powershellRollback: 'N/A',
    verifiedBy: 'Rigorset Security Audit',
    antiCheatImpact: 'COMPATIBLE',
  },
  {
    id: 'discard-02',
    title: 'Completely Disabling Pagefile (Virtual Memory)',
    category: 'System Kernel',
    description: 'Turns off Windows paging file under the myth that 16GB/32GB RAM never needs paging.',
    riskLevel: 'DISCARDED',
    isApplied: false,
    expectedBenefit: 'FALSE PROMISE: Claimed to save SSD writes.',
    technicalDetails: 'Sets `PagingFiles` registry key to empty string.',
    whyDiscardedOrWarning:
      'DISCARDED & HIGH RISK: Causes immediate Out-Of-Memory application crashes (Call of Duty, Photoshop, CAD tools), disables BSOD crash dump logging, and breaks Windows memory mapping routines.',
    powershellApply: '# BLOCKED: System Pagefile must remain automatically managed by Windows 11.',
    powershellRollback: 'Set-CimInstance -Query "Select * from Win32_ComputerSystem" -Property @{AutomaticManagedPagefile = $true}',
    verifiedBy: 'Windows 11 Hardware Lab',
    antiCheatImpact: 'COMPATIBLE',
  },
  {
    id: 'discard-03',
    title: 'Disabling Windows Update Service (wuauserv)',
    category: 'Privacy & Services',
    description: 'Permanently stops and disables Windows Update service.',
    riskLevel: 'DISCARDED',
    isApplied: false,
    expectedBenefit: 'FALSE PROMISE: Stops background updates.',
    technicalDetails: 'Executes `Set-Service wuauserv -StartupType Disabled`.',
    whyDiscardedOrWarning:
      'DISCARDED & HIGH RISK: Breaks Xbox Game Pass app installs, blocks critical zero-day security patches, and prevents Microsoft Store app updates.',
    powershellApply: '# BLOCKED: Rigorset recommends Pause Updates (1-3 weeks) instead of disabling service.',
    powershellRollback: 'Set-Service wuauserv -StartupType Automatic',
    verifiedBy: 'Rigorset Security Audit',
    antiCheatImpact: 'WARNING_EAC',
  },
  {
    id: 'discard-04',
    title: 'Unchecked Registry Cleaner Scripts',
    category: 'System Kernel',
    description: 'Scans and deletes "orphan" registry keys using regex patterns.',
    riskLevel: 'DISCARD_SNAKE_OIL',
    isApplied: false,
    expectedBenefit: 'NEGLIGIBLE: Saves < 2KB of registry hive space.',
    technicalDetails: 'Mass deletion of registry subkeys under HKLM\\Software.',
    whyDiscardedOrWarning:
      'DISCARDED & DANGEROUS: High risk of corrupting COM registration, context menus, driver GUID associations, and system activation keys with ZERO measurable performance boost.',
    powershellApply: '# BLOCKED: Rigorset uses target-specific integrity verification only.',
    powershellRollback: 'N/A',
    verifiedBy: 'Rigorset Security Audit',
    antiCheatImpact: 'COMPATIBLE',
  },
  {
    id: 'discard-05',
    title: 'Global Core Parking Disabling on Laptops',
    category: 'Gaming & GPU',
    description: 'Forces all CPU cores (including Efficiency cores) to remain 100% active at all times.',
    riskLevel: 'RISKY',
    isApplied: false,
    expectedBenefit: 'Negligible 0.5% latency change on desktop CPUs.',
    technicalDetails: 'Sets Power Plan `0cc5b647-c1df-4596-858a-6761013bc94e` to 0%.',
    whyDiscardedOrWarning:
      'MEDIUM/HIGH RISK: On laptops and handhelds (ROG Ally, Legion Go), this causes severe battery drain, high thermal idling (65°C+), fan noise, and thermal throttling under sustained load.',
    powershellApply: 'powercfg -setacvalueindex SCHEME_CURRENT SUB_PROCESSOR 0cc5b647-c1df-4596-858a-6761013bc94e 0',
    powershellRollback: 'powercfg -setacvalueindex SCHEME_CURRENT SUB_PROCESSOR 0cc5b647-c1df-4596-858a-6761013bc94e 100',
    verifiedBy: 'Community Verified',
    antiCheatImpact: 'COMPATIBLE',
  },
];
export const INITIAL_GAME_PROFILES: GameProfile[] = [
  {
    id: 'game-cod',
    title: 'Call of Duty: Warzone & BO6',
    genre: 'FPS / Battle Royale',
    iconName: 'Crosshair',
    installed: true,
    installPath: 'C:\\SteamLibrary\\steamapps\\common\\Call of Duty HQ\\cod.exe',
    detectedLauncher: 'Steam',
    executableName: 'cod.exe',
    active: true,
    gpuPriority: 'Realtime',
    gpuSchedulingEnabled: true,
    networkPriorityEnabled: true,
    networkQosTag: 'DSCP 46 (Expedited Forwarding)',
    hagsRecommended: true,
    shaderCacheMb: 10240,
    workerThreads: 12,
    lowLatencyMode: 'Reflex Boost',
    customPowerShell: 'Set-ItemProperty -Path "HKLM:\\SOFTWARE\\Microsoft\\DirectX" -Name "MaxShaderCacheSize" -Value 10240; Set-Process -Name "Cod" -Priority High',
    description: 'Enforces High-Priority GPU scheduling, pre-allocates 10GB DX12 shader cache, and optimizes CPU worker thread count to eliminate VRAM stuttering in Urzikstan.',
    fpsGainPct: 14.2,
    stutterReductionPct: 32,
  },
  {
    id: 'game-fortnite',
    title: 'Fortnite (Unreal Engine 5.4)',
    genre: 'FPS / Battle Royale',
    iconName: 'Gamepad2',
    installed: true,
    installPath: 'C:\\Program Files\\Epic Games\\Fortnite\\FortniteGame\\Binaries\\Win64\\FortniteClient-Win64-Shipping.exe',
    detectedLauncher: 'Epic Games',
    executableName: 'FortniteClient-Win64-Shipping.exe',
    active: false,
    gpuPriority: 'High',
    gpuSchedulingEnabled: true,
    networkPriorityEnabled: true,
    networkQosTag: 'DSCP 46 (Expedited Forwarding)',
    hagsRecommended: true,
    shaderCacheMb: 8192,
    workerThreads: 8,
    lowLatencyMode: 'Reflex Boost',
    customPowerShell: 'Set-ItemProperty -Path "HKCU:\\Software\\Epic Games\\Fortnite" -Name "LowLatency" -Value 1',
    description: 'Locks DirectX 12 rendering pipelines, flushes pre-compiled PSO caches, and disables background Windows Search Indexer during matchmaking.',
    fpsGainPct: 18.5,
    stutterReductionPct: 45,
  },
  {
    id: 'game-cyberpunk',
    title: 'Cyberpunk 2077: Phantom Liberty',
    genre: 'Open World RPG',
    iconName: 'Zap',
    installed: true,
    installPath: 'C:\\GOG Games\\Cyberpunk 2077\\bin\\x64\\Cyberpunk2077.exe',
    detectedLauncher: 'Steam',
    executableName: 'Cyberpunk2077.exe',
    active: false,
    gpuPriority: 'Realtime',
    gpuSchedulingEnabled: true,
    networkPriorityEnabled: false,
    networkQosTag: 'Standard (Offline Solo)',
    hagsRecommended: true,
    shaderCacheMb: 12288,
    workerThreads: 16,
    lowLatencyMode: 'Reflex Boost',
    customPowerShell: 'Set-ItemProperty -Path "HKLM:\\SYSTEM\\CurrentControlSet\\Control\\Session Manager\\Memory Management" -Name "LargeSystemCache" -Value 1',
    description: 'Maximizes Ray Tracing & Frame Generation queue sizes, allocates LargeSystemCache, and tunes Thread Affinity across P-Cores and E-Cores.',
    fpsGainPct: 11.8,
    stutterReductionPct: 28,
  },
  {
    id: 'game-valorant',
    title: 'VALORANT (Riot Vanguard Safe)',
    genre: 'Tactical Shooter',
    iconName: 'Shield',
    installed: true,
    installPath: 'C:\\Riot Games\\VALORANT\\live\\ShooterGame\\Binaries\\Win64\\VALORANT-Win64-Shipping.exe',
    detectedLauncher: 'Riot Client',
    executableName: 'VALORANT-Win64-Shipping.exe',
    active: true,
    gpuPriority: 'High',
    gpuSchedulingEnabled: true,
    networkPriorityEnabled: true,
    networkQosTag: 'DSCP 46 High-Yield QoS',
    hagsRecommended: true,
    shaderCacheMb: 4096,
    workerThreads: 6,
    lowLatencyMode: 'Reflex Boost',
    customPowerShell: '# Vanguard Compliant: Sets High Interrupt Rate on Wi-Fi/NIC and forces 1000Hz polling rate',
    description: 'Strict Vanguard Anti-Cheat compliance guaranteed! Lowers DPC network interrupt latency, locks process CPU core 0-7 affinity, and enforces raw mouse input polling.',
    fpsGainPct: 22.1,
    stutterReductionPct: 50,
  },
  {
    id: 'game-apex',
    title: 'Apex Legends (Easy Anti-Cheat)',
    genre: 'Battle Royale',
    iconName: 'Flame',
    installed: false,
    installPath: 'C:\\Program Files (x86)\\Steam\\steamapps\\common\\Apex Legends\\r5apex.exe',
    detectedLauncher: 'Steam',
    executableName: 'r5apex.exe',
    active: false,
    gpuPriority: 'High',
    gpuSchedulingEnabled: false,
    networkPriorityEnabled: true,
    networkQosTag: 'DSCP 46 High-Yield QoS',
    hagsRecommended: true,
    shaderCacheMb: 8192,
    workerThreads: 8,
    lowLatencyMode: 'Anti-Lag+',
    customPowerShell: '# EAC Safe optimizations for Source Engine',
    description: 'Optimizes Source Engine FPS cap overrides, adjusts DirectX command buffers, and clears audio channel buffer latency.',
    fpsGainPct: 13.5,
    stutterReductionPct: 30,
  },
  {
    id: 'game-cs2',
    title: 'Counter-Strike 2 (Source 2)',
    genre: 'Tactical FPS',
    iconName: 'Target',
    installed: true,
    installPath: 'C:\\Program Files (x86)\\Steam\\steamapps\\common\\Counter-Strike Global Offensive\\game\\bin\\win64\\cs2.exe',
    detectedLauncher: 'Steam',
    executableName: 'cs2.exe',
    active: false,
    gpuPriority: 'Realtime',
    gpuSchedulingEnabled: true,
    networkPriorityEnabled: true,
    networkQosTag: 'DSCP 46 Sub-Tick QoS Packet Priority',
    hagsRecommended: true,
    shaderCacheMb: 8192,
    workerThreads: 12,
    lowLatencyMode: 'Reflex Boost',
    customPowerShell: 'Set-ItemProperty -Path "HKLM:\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile\\Tasks\\Games" -Name "GPU Priority" -Value 8',
    description: 'Source 2 Vulkan/DX11 pipeline tuning, Sub-Tick packet queue prioritization, and Windows Multimedia SystemProfile Game priority level 8.',
    fpsGainPct: 16.8,
    stutterReductionPct: 38,
  },
];

export const INITIAL_STARTUP_APPS: StartupApp[] = [
  {
    id: 'su-01',
    name: 'Spotify Web Helper',
    publisher: 'Spotify AB',
    impact: 'High',
    enabled: false,
    bootDelaySec: 4.5,
    ramUsageMb: 380,
    path: 'C:\\Users\\User\\AppData\\Roaming\\Spotify\\Spotify.exe',
  },
  {
    id: 'su-02',
    name: 'Discord Startup Launcher',
    publisher: 'Discord Inc.',
    impact: 'High',
    enabled: false,
    bootDelaySec: 3.8,
    ramUsageMb: 420,
    path: 'C:\\Users\\User\\AppData\\Local\\Discord\\Update.exe',
  },
  {
    id: 'su-03',
    name: 'Microsoft OneDrive Background Sync',
    publisher: 'Microsoft Corporation',
    impact: 'High',
    enabled: false,
    bootDelaySec: 5.2,
    ramUsageMb: 290,
    path: 'C:\\Program Files\\Microsoft OneDrive\\OneDrive.exe',
  },
  {
    id: 'su-04',
    name: 'Steam Client WebHelper',
    publisher: 'Valve Corporation',
    impact: 'Medium',
    enabled: true,
    bootDelaySec: 2.1,
    ramUsageMb: 340,
    path: 'C:\\Program Files (x86)\\Steam\\steam.exe',
  },
  {
    id: 'su-05',
    name: 'Epic Games Launcher',
    publisher: 'Epic Games Inc.',
    impact: 'High',
    enabled: false,
    bootDelaySec: 4.1,
    ramUsageMb: 510,
    path: 'C:\\Program Files (x86)\\Epic Games\\Launcher\\Portal\\Binaries\\Win64\\EpicGamesLauncher.exe',
  },
];

export const INITIAL_ANTI_CHEAT_ENGINES: AntiCheatEngine[] = [
  {
    id: 'ac-vanguard',
    name: 'Riot Vanguard Kernel Driver (vgc)',
    developer: 'Riot Games',
    protectedGames: ['VALORANT', 'League of Legends'],
    hvciRequired: true,
    testSigningAllowed: false,
    activeStatus: 'ACTIVE_GUARD',
    riskAlertsCount: 0,
  },
  {
    id: 'ac-eac',
    name: 'Easy Anti-Cheat (EOS)',
    developer: 'Epic Games',
    protectedGames: ['Fortnite', 'Apex Legends', 'Elden Ring', 'Rust'],
    hvciRequired: false,
    testSigningAllowed: false,
    activeStatus: 'ACTIVE_GUARD',
    riskAlertsCount: 0,
  },
  {
    id: 'ac-battleye',
    name: 'BattEye Anti-Cheat',
    developer: 'BattEye Innovations',
    protectedGames: ['Rainbow Six Siege', 'Destiny 2', 'DayZ', 'PUBG'],
    hvciRequired: false,
    testSigningAllowed: false,
    activeStatus: 'ACTIVE_GUARD',
    riskAlertsCount: 0,
  },
  {
    id: 'ac-ricochet',
    name: 'RICOCHET Kernel Driver',
    developer: 'Activision',
    protectedGames: ['Call of Duty: Warzone', 'Modern Warfare III', 'Black Ops 6'],
    hvciRequired: true,
    testSigningAllowed: false,
    activeStatus: 'ACTIVE_GUARD',
    riskAlertsCount: 0,
  },
];

export const INITIAL_UEFI_PROVIDERS: UefiVendorProvider[] = [
  {
    vendor: 'ASUS ROG',
    wmiNamespace: 'root\\wmi\\ASUSWMI',
    cStatesConfigurable: true,
    pboLimitControl: true,
    secureBootStatus: 'ENABLED',
    bitlockerSafetyStatus: 'SAFE',
  },
  {
    vendor: 'MSI Dragon',
    wmiNamespace: 'root\\wmi\\MSI_WMI',
    cStatesConfigurable: true,
    pboLimitControl: true,
    secureBootStatus: 'ENABLED',
    bitlockerSafetyStatus: 'SAFE',
  },
  {
    vendor: 'Gigabyte',
    wmiNamespace: 'root\\wmi\\GIGABYTE_WMI',
    cStatesConfigurable: true,
    pboLimitControl: true,
    secureBootStatus: 'ENABLED',
    bitlockerSafetyStatus: 'SAFE',
  },
  {
    vendor: 'Lenovo Legion',
    wmiNamespace: 'root\\wmi\\Lenovo_Wmi',
    cStatesConfigurable: true,
    pboLimitControl: false,
    secureBootStatus: 'ENABLED',
    bitlockerSafetyStatus: 'SAFE',
  },
];

export const INITIAL_DRIVERS: DriverItem[] = [
  {
    id: 'drv-01',
    deviceName: 'NVIDIA GeForce RTX 4070 Ti / 5070 Series',
    category: 'GPU',
    vendor: 'NVIDIA',
    installedVersion: '551.86 WHQL',
    latestVersion: '556.12 WHQL',
    releaseDate: '2026-07-28',
    status: 'UPDATE_RECOMMENDED',
    whqlCertified: true,
    stabilityRating: 98,
    patchNotes: 'Fixes DLSS 3.5 Frame Generation memory leak and reduces micro-stutter in Unreal Engine 5.4 games.',
    downloadUrl: 'https://www.nvidia.com/Download/index.aspx',
  },
  {
    id: 'drv-02',
    deviceName: 'Intel Wi-Fi 6E / Wi-Fi 7 AX211 Controller',
    category: 'Network',
    vendor: 'Intel',
    installedVersion: '23.40.0.4',
    latestVersion: '23.60.1.2',
    releaseDate: '2026-08-01',
    status: 'UPDATE_RECOMMENDED',
    whqlCertified: true,
    stabilityRating: 99,
    patchNotes: 'Fixes random 6GHz band disconnects on WPA3 Enterprise and lowers Wi-Fi packet latency jitter.',
    downloadUrl: 'https://www.intel.com/content/www/us/en/download-center/home.html',
  },
  {
    id: 'drv-03',
    deviceName: 'Realtek High Definition Audio ALC1220',
    category: 'Audio',
    vendor: 'Realtek',
    installedVersion: '6.0.9620.1',
    latestVersion: '6.0.9620.1',
    releaseDate: '2026-05-12',
    status: 'UP_TO_DATE',
    whqlCertified: true,
    stabilityRating: 100,
    patchNotes: 'Current driver is optimal. Verified WHQL digital signature.',
    downloadUrl: 'https://www.realtek.com',
  },
  {
    id: 'drv-04',
    deviceName: 'AMD Ryzen 7000/9000 Series Chipset Driver',
    category: 'Chipset',
    vendor: 'AMD',
    installedVersion: '6.02.07.2300',
    latestVersion: '6.07.15.011',
    releaseDate: '2026-07-15',
    status: 'CRITICAL',
    whqlCertified: true,
    stabilityRating: 96,
    patchNotes: 'Critical update: Fixes core parking thread scheduler assignments for Dual CCD processors (7950X3D / 9950X).',
    downloadUrl: 'https://www.amd.com/en/support',
  },
];

export const INITIAL_MAINTENANCE_STEPS: MaintenanceStep[] = [
  {
    id: 'JUNK_CLEAN',
    nameKey: '1-Click System Junk & Cache Purge',
    descriptionKey: 'Clean Temp folders, DirectX shader cache, Delivery Optimization, and browser caches.',
    itemsFound: 482,
    spacePotentialMb: 4280,
    riskLevel: 'SAFE',
    status: 'PENDING',
    log: [],
  },
  {
    id: 'MEMORY_TURBO',
    nameKey: 'Windows 11 Safe Memory Compression',
    descriptionKey: 'Compress stale background process memory into physical RAM without disk thrashing.',
    itemsFound: 14,
    spacePotentialMb: 2400,
    riskLevel: 'SAFE',
    status: 'PENDING',
    log: [],
  },
  {
    id: 'STARTUP_IMPACT',
    nameKey: 'Startup Impact Streamlining',
    descriptionKey: 'Disable heavy auto-launching launchers and background updater telemetry.',
    itemsFound: 6,
    spacePotentialMb: 0,
    riskLevel: 'SAFE',
    status: 'PENDING',
    log: [],
  },
  {
    id: 'TELEMETRY',
    nameKey: 'Privacy & Diagnostic Tracking Tweak',
    descriptionKey: 'Disable DiagTrack customer experience feedback and telemetry bandwidth usage.',
    itemsFound: 3,
    spacePotentialMb: 120,
    riskLevel: 'SAFE',
    status: 'PENDING',
    log: [],
  },
  {
    id: 'DRIVER_RADAR',
    nameKey: 'WHQL Hardware Driver Check',
    descriptionKey: 'Audit graphics, chipset, and network drivers for critical stability patches.',
    itemsFound: 2,
    spacePotentialMb: 0,
    riskLevel: 'SAFE',
    status: 'PENDING',
    log: [],
  },
  {
    id: 'REGISTRY_INTEGRITY',
    nameKey: 'Targeted Registry & Path Integrity',
    descriptionKey: 'Safely fix invalid shell paths and broken file association references.',
    itemsFound: 18,
    spacePotentialMb: 5,
    riskLevel: 'SAFE',
    status: 'PENDING',
    log: [],
  },
];

export const INITIAL_CHANGE_JOURNAL_ENTRIES: ChangeJournalEntry[] = [
  {
    id: 'jrn-101',
    timestamp: '2026-08-12 06:45:12',
    optimizationId: 'OPT-GPU-HAGS',
    title: 'Hardware-Accelerated GPU Scheduling (HAGS)',
    category: 'Gaming & GPU',
    previousState: 'HKLM:\\...\\GraphicsDrivers\\HwSchMode = 1 (Disabled)',
    requestedState: 'HwSchMode = 2 (Hardware Enabled)',
    resultingState: 'HwSchMode = 2 (Hardware Enabled)',
    success: true,
    verificationResult: 'Verified Registry Integrity',
    benchmarkDelta: '-4.2ms DX12 Render Latency',
    rollbackAvailable: true,
    maturityLevel: 'LEVEL_5_PUBLIC_PRODUCTION',
  },
  {
    id: 'jrn-102',
    timestamp: '2026-08-12 06:45:15',
    optimizationId: 'OPT-NET-NAGLE',
    title: 'Nagle Algorithm & TCP Latency Queue Bypass',
    category: 'Network',
    previousState: 'TcpAckFrequency = NotConfigured (Default 2)',
    requestedState: 'TcpAckFrequency = 1, TCPNoDelay = 1',
    resultingState: 'TcpAckFrequency = 1, TCPNoDelay = 1',
    success: true,
    verificationResult: 'Verified Adapter Binding',
    benchmarkDelta: '-6ms Ping Jitter in Valorant',
    rollbackAvailable: true,
    maturityLevel: 'LEVEL_4_VALIDATED',
  },
  {
    id: 'jrn-103',
    timestamp: '2026-08-12 06:45:18',
    optimizationId: 'OPT-MEM-COMP',
    title: 'Windows 11 MMAgent Memory Compression',
    category: 'Memory',
    previousState: 'MemoryCompression = Disabled',
    requestedState: 'Enable-MMAgent -MemoryCompression',
    resultingState: 'MemoryCompression = Active',
    success: true,
    verificationResult: 'Verified MMAgent Service',
    benchmarkDelta: '+2.4GB Available RAM',
    rollbackAvailable: true,
    maturityLevel: 'LEVEL_5_PUBLIC_PRODUCTION',
  },
  {
    id: 'jrn-104',
    timestamp: '2026-08-12 06:45:22',
    optimizationId: 'OPT-GAME-COD',
    title: 'Call of Duty DX12 Shader Cache Pre-allocation',
    category: 'Gaming & GPU',
    previousState: 'MaxShaderCacheSize = 1024 (Default 1GB)',
    requestedState: 'MaxShaderCacheSize = 10240 (10GB)',
    resultingState: 'MaxShaderCacheSize = 10240 (10GB)',
    success: true,
    verificationResult: 'Verified DirectX Registry',
    benchmarkDelta: '+14% 1% Low FPS in Urzikstan',
    rollbackAvailable: true,
    maturityLevel: 'LEVEL_4_VALIDATED',
  },
];
