import { CheckCircle2, ClipboardCheck, LoaderCircle, ShieldAlert } from 'lucide-react';
import type { MaintenanceAction } from '../types';

interface MaintenanceQueueProps {
  actions: MaintenanceAction[];
  activeActionId: string | null;
  error: string | null;
  onExecute: (action: MaintenanceAction) => void;
}

export function MaintenanceQueue({ actions, activeActionId, error, onExecute }: MaintenanceQueueProps) {
  return <div className="space-y-6"><section className="rounded-2xl border border-slate-800 bg-slate-900/70 p-6"><div className="flex items-start gap-3"><ClipboardCheck className="mt-0.5 h-5 w-5 text-cyan-400" /><div><h2 className="text-xl font-bold text-white">Itemized maintenance queue</h2><p className="mt-1 max-w-2xl text-sm leading-relaxed text-slate-400">Each action is based on the most recent native scan. There is no bulk “boost” command: you review and run actions one at a time.</p></div></div><div className="mt-4 flex gap-2 rounded-lg border border-amber-500/25 bg-amber-950/20 p-3 text-xs text-amber-100/90"><ShieldAlert className="h-4 w-4 shrink-0 text-amber-300" />Clearing temporary files is not reversible. ReTRIM does not modify a persistent setting. Both outcomes are logged locally with the operating-system exit result.</div></section>{error && <p className="rounded-lg border border-rose-500/30 bg-rose-950/30 p-3 text-xs text-rose-200">{error}</p>}<section className="grid gap-4 lg:grid-cols-2">{actions.map((action) => { const running = action.id === activeActionId; return <article key={action.id} className="rounded-xl border border-slate-800 bg-slate-900/70 p-5"><div className="flex items-start justify-between gap-4"><div><h3 className="font-semibold text-slate-100">{action.title}</h3><p className="mt-1 text-xs leading-relaxed text-slate-400">{action.description}</p></div><span className={`shrink-0 rounded px-2 py-1 text-[10px] font-semibold ${action.reversible ? 'bg-emerald-500/10 text-emerald-300' : 'bg-amber-500/10 text-amber-300'}`}>{action.reversible ? 'REVERSIBLE' : 'NOT REVERSIBLE'}</span></div><div className="mt-4 rounded-lg bg-slate-950/70 p-3 text-xs text-cyan-200"><span className="font-semibold text-cyan-400">Scan evidence: </span>{action.evidence}</div><button onClick={() => onExecute(action)} disabled={Boolean(activeActionId)} className="mt-4 inline-flex items-center gap-2 rounded-lg bg-cyan-400 px-3 py-2 text-xs font-bold text-slate-950 disabled:cursor-not-allowed disabled:opacity-50">{running ? <LoaderCircle className="h-3.5 w-3.5 animate-spin" /> : <CheckCircle2 className="h-3.5 w-3.5" />}{running ? 'Running…' : 'Review and run'}</button></article>; })}</section>{actions.length === 0 && <section className="rounded-xl border border-slate-800 bg-slate-900/70 p-6 text-sm text-slate-400">No executable maintenance actions were identified. You can still review the verified scan and local history.</section>}</div>;
}
