function deepFreeze(value) {
  if (!value || typeof value !== 'object' || Object.isFrozen(value)) return value;
  Object.freeze(value);
  for (const child of Object.values(value)) deepFreeze(child);
  return value;
}

const GAME_SETTINGS_GUIDES = deepFreeze([
  {
    id: 'fortnite-pc-performance-review',
    game: 'Fortnite',
    platform: 'Windows PC',
    status: 'VERIFIED_GUIDANCE',
    lastReviewed: '2026-08-25',
    objective: 'Competitive frame-rate and stable pacing with explicit visual-quality tradeoffs.',
    applicability: 'Use as a review guide for the current in-game Video settings. Hardware limits, display refresh, thermals, drivers, and the selected game mode can change the result.',
    automation: 'GUIDANCE_ONLY',
    ongoingTesting: 'Ongoing verification: change one setting group at a time, restart when the game requires it, and compare at least three matched captures of the same replay or scene. Restore the prior value when the result is noisy, neutral, or adverse.',
    settings: [
      {
        id: 'rendering-mode',
        label: 'Rendering mode',
        recommendation: 'Use Fortnite’s Performance — Lower Graphical Fidelity mode when frame rate is the priority and reduced visual fidelity is acceptable.',
        rationale: 'Epic documents this built-in mode as an option that may raise FPS, particularly on lower-performance hardware.',
        tradeoff: 'Lower visual quality; the game must be restarted. DirectX 12 can remain preferable when image quality or a different stability profile matters more.',
        verification: 'Restart Fortnite, repeat the same scene, and compare frame-time consistency as well as average FPS.',
      },
      {
        id: 'vertical-sync-and-cap',
        label: 'V-Sync and frame cap',
        recommendation: 'Turn V-Sync off when deliberately choosing a frame-rate limit that differs from the display refresh rate, then set an intentional cap instead of assuming Unlimited is best.',
        rationale: 'Epic explains that V-Sync ties FPS to display refresh and that a chosen cap can be adjusted after V-Sync is disabled.',
        tradeoff: 'Disabling V-Sync can introduce tearing. Unlimited FPS can increase heat, power use, and frame-time variance on a bottlenecked system.',
        verification: 'Test the same gameplay segment with a stable cap and with the prior setting; retain the option with better repeatability and acceptable tearing.',
      },
      {
        id: 'three-d-resolution',
        label: '3D resolution',
        recommendation: 'Begin at 100% so the comparison preserves native render scale; reduce it only when GPU load is the demonstrated bottleneck.',
        rationale: 'Epic’s graphics troubleshooting starts from 100% 3D resolution and recommends changing quality gradually to find a stable balance.',
        tradeoff: 'Lower render scale can improve GPU-limited performance but reduces image clarity and can make distant detail harder to read.',
        verification: 'Record GPU utilization, frame times, and image clarity in the same scene before lowering render scale.',
      },
      {
        id: 'ray-tracing',
        label: 'Ray tracing',
        recommendation: 'Keep ray tracing off for a competitive performance-focused profile.',
        rationale: 'Epic states that ray tracing significantly reduces frame rate and is unavailable in Performance mode.',
        tradeoff: 'Reflections, shadows, global illumination, and ambient-occlusion quality are reduced.',
        verification: 'Confirm the setting is off after restart and compare the same GPU-limited scene if visual quality is a competing priority.',
      },
      {
        id: 'high-resolution-textures',
        label: 'High-resolution texture package',
        recommendation: 'Treat removal as an optional storage choice for Performance-mode users, not as a guaranteed FPS tweak.',
        rationale: 'Epic documents the optional texture package as removable to reduce installation size and says it may also help some systems.',
        tradeoff: 'Lower texture detail and a launcher-managed install change; downloading again may be required to restore the package.',
        verification: 'Record available storage and texture quality first. Do not attribute an FPS change without a matched before/after capture.',
      },
    ],
    sources: [
      {
        title: 'Epic Games — Enable Performance mode in Fortnite',
        url: 'https://www.epicgames.com/help/c-Category_EpicAccounts/c-202300000001755/a202300000013270?lang=en-US',
      },
      {
        title: 'Epic Games — Adjust a locked or capped FPS',
        url: 'https://www.epicgames.com/help/c-202300000001636/c-202300000001719/how-do-i-adjust-my-fps-in-fortnite-if-it-is-locked-or-capped-a202300000010554?lang=en-US',
      },
      {
        title: 'Epic Games — Troubleshoot graphics problems',
        url: 'https://www.epicgames.com/help/c-202300000001636/c-202300000001719/fix-graphics-problems-in-fortnite-a202300000013484?lang=en-US',
      },
      {
        title: 'Epic Games — Fortnite ray tracing support',
        url: 'https://www.epicgames.com/help/c-202300000001636/c-202300000001721/does-fortnite-support-ray-tracing-a202300000011393',
      },
    ],
  },
  {
    id: 'apex-legends-pc-performance-review',
    game: 'Apex Legends',
    platform: 'Windows PC',
    status: 'VERIFIED_GUIDANCE',
    lastReviewed: '2026-08-25',
    objective: 'Competitive responsiveness and stable frame pacing using EA-published settings guidance.',
    applicability: 'Start from monitor-native resolution and change one GPU-heavy group at a time. The right cap and texture budget depend on display refresh, VRAM, thermals, and whether the system is CPU- or GPU-limited.',
    automation: 'GUIDANCE_ONLY',
    ongoingTesting: 'Use the in-game performance display or the same external capture tool, repeat the same route or firing-range sequence at least three times, and keep a prior-settings note before changing the next group.',
    settings: [
      {
        id: 'display-mode',
        label: 'Display mode and resolution',
        recommendation: 'Use fullscreen for a single-monitor performance review and keep the display’s native aspect ratio and resolution as the comparison baseline.',
        rationale: 'EA lists fullscreen for one monitor and monitor-default aspect ratio and resolution as its starting point.',
        tradeoff: 'Fullscreen can make task switching less convenient; multi-monitor workflows may favor windowed modes.',
        verification: 'Confirm the active refresh rate and compare the same sequence without changing resolution and quality simultaneously.',
      },
      {
        id: 'reflex-vsync',
        label: 'NVIDIA Reflex and V-Sync',
        recommendation: 'Enable NVIDIA Reflex on a supported NVIDIA GPU. Leave V-Sync disabled for the competitive baseline unless tearing is unacceptable.',
        rationale: 'EA recommends Reflex when supported and V-Sync disabled unless screen tearing is present.',
        tradeoff: 'Disabling V-Sync can tear; Reflex availability and effect depend on the GPU, driver, and bottleneck.',
        verification: 'Compare input response and frame-time consistency with the same cap and scene; restore V-Sync if tearing outweighs the latency tradeoff.',
      },
      {
        id: 'advanced-quality',
        label: 'Advanced quality load',
        recommendation: 'For a competitive profile, begin with ambient occlusion, volumetric lighting, dynamic spot shadows, and high-detail effects disabled or low.',
        rationale: 'EA’s competitive starting point reduces these GPU-heavy settings while keeping changes inside the game UI.',
        tradeoff: 'Lighting, shadows, model detail, effects, and environmental richness are reduced.',
        verification: 'Raise one category at a time after establishing a stable baseline; retain only changes that fit the frame-time budget.',
      },
      {
        id: 'fps-cap',
        label: 'Intentional FPS cap',
        recommendation: 'Use the launcher-supported +fps_max value only when you have chosen a cap appropriate to the display and repeatable workload.',
        rationale: 'EA documents the launch option and warns that changing the cap can cause performance issues.',
        tradeoff: 'An unsuitable cap can worsen pacing or add unnecessary GPU load; copying another system’s value is not reliable.',
        verification: 'Compare at least three matched runs at the prior cap and candidate cap, including thermals and low-percentile frame times.',
      },
    ],
    sources: [
      {
        title: 'EA Help — Best Apex Legends settings on PC',
        url: 'https://help.ea.com/en/articles/apex-legends/best-settings-pc/',
      },
      {
        title: 'EA Help — Show, change, and cap Apex Legends FPS',
        url: 'https://help.ea.com/en/articles/apex-legends/change-and-cap-fps/',
      },
    ],
  },
  {
    id: 'call-of-duty-black-ops-7-performance-review',
    game: 'Call of Duty: Black Ops 7',
    platform: 'Windows PC · Battle.net / Steam / Xbox app',
    status: 'VERIFIED_GUIDANCE',
    lastReviewed: '2026-08-29',
    objective: 'Review current in-game display, quality and upscaling controls for competitive frame pacing without importing another PC’s template.',
    applicability: 'This is manual Black Ops 7 guidance, not an executable profile. A dated user-supplied public checklist helped identify settings worth reviewing, but its values are community evidence rather than publisher certification. Dialed does not copy template files, write versioned cod25 files, alter launcher arguments, or touch RICOCHET, TPM, Secure Boot or account state.',
    automation: 'GUIDANCE_ONLY',
    ongoingTesting: 'Record the original in-game values, change one group at a time, restart when requested, and compare at least three matched private-match or benchmark runs. Keep an intentional frame cap and record GPU utilization, VRAM, frame times and visual clarity; restore the prior group when the result is neutral or worse.',
    settings: [
      {
        id: 'display-baseline',
        label: 'Display mode, refresh and render scale',
        recommendation: 'Verify the active Windows refresh rate, then begin with monitor-native resolution and 100% render resolution. Test exclusive fullscreen only when the current menu offers it and display switching remains stable.',
        rationale: 'Activision describes Black Ops 7 as a PC build with granular graphics controls and defines its competitive target around high frame rate on a high-refresh monitor. A read-only current local schema confirms separate display-mode, refresh-rate and render-scale fields, but does not establish one universal optimum.',
        tradeoff: 'Exclusive fullscreen can make task switching less convenient. Native render scale preserves clarity but can be too demanding when the GPU is the measured bottleneck.',
        verification: 'Confirm the active display mode after restart and compare the same run before changing any quality or upscaling controls.',
      },
      {
        id: 'cap-sync-latency',
        label: 'Frame cap, V-Sync and supported latency control',
        recommendation: 'Choose a deliberate in-game frame cap for the display and workload instead of treating Off, 300 or 600 FPS as universal. Test V-Sync off only when tearing is acceptable; on supported NVIDIA hardware, compare the in-game Reflex option without stacking driver overrides.',
        rationale: 'Activision’s competitive specification is outcome-based rather than a fixed cap, and NVIDIA confirms Black Ops 7 support for Reflex. The supplied community checklist is useful as a test lead, not proof that one cap or sync state fits every system.',
        tradeoff: 'A cap that is too high can increase heat and frame-time variance; V-Sync off can tear; latency features behave differently under CPU and GPU bottlenecks.',
        verification: 'Hold resolution and quality constant, then compare frame-time consistency, thermals and tearing across the prior and candidate cap/sync state.',
      },
      {
        id: 'competitive-quality-groups',
        label: 'Effects, shadows, reflections and textures',
        recommendation: 'For a performance-focused baseline, test motion effects, depth of field, particles, shader load, screen-space shadows, ambient lighting, weather volumes and reflections at lower values one group at a time. Size texture resolution and filtering to measured VRAM headroom and clarity needs instead of forcing every texture control to Low.',
        rationale: 'Black Ops 7 exposes fine-grained graphics controls. The current local schema confirms these setting families still exist; the benefit of each value remains scene-, GPU- and VRAM-dependent.',
        tradeoff: 'Lowering these groups reduces lighting, material, shadow and environmental detail. Very low textures or filtering can make distant surfaces harder to read without fixing a CPU bottleneck.',
        verification: 'Use a visually busy repeatable scene, retain the native render scale, and raise back any group whose visual loss exceeds its repeatable frame-time benefit.',
      },
      {
        id: 'one-upscaler',
        label: 'Use one supported upscaling path',
        recommendation: 'Choose only the in-game upscaling or anti-aliasing path supported by the installed GPU. Start from native or a Quality mode; try Balanced only after confirming a GPU bottleneck. Treat frame generation separately from rendered-frame latency.',
        rationale: 'Activision documents AMD FSR support and NVIDIA documents DLSS and Reflex support for Black Ops 7. Those technologies improve different parts of the pipeline and do not justify enabling every available accelerator together.',
        tradeoff: 'More aggressive upscaling reduces image clarity, while generated frames can raise displayed FPS without equivalent input-response improvement or low-percentile stability.',
        verification: 'Record render resolution, generated-frame state and GPU utilization, then compare image clarity and raw frame-time evidence rather than the displayed FPS counter alone.',
      },
      {
        id: 'input-audio-boundary',
        label: 'Input and audio remain personal controls',
        recommendation: 'Keep raw mouse input enabled when it behaves correctly, but do not copy another player’s sensitivity, polling rate or audio mix as an FPS optimization. Use Dialed’s separate Input Devices evidence for polling compatibility and keep volume/channel choices based on comfort and audibility.',
        rationale: 'Black Ops 7 exposes independent input and audio controls. The photographed list mixes competitive preferences with graphics recommendations; those preferences are not evidence of higher frame rate or universally lower latency.',
        tradeoff: 'A higher polling rate can add CPU work on some systems, and an imported audio mix can reduce accessibility or situational cues. Personal control changes can be harder to notice than graphics changes.',
        verification: 'Change input or audio only after the graphics baseline is stable, record the prior value, and test in a private environment before using it competitively.',
      },
    ],
    sources: [
      {
        title: 'Call of Duty — Black Ops 7 on PC',
        url: 'https://www.callofduty.com/blackops7/pc',
      },
      {
        title: 'Activision Support — Black Ops 7 PC requirements',
        url: 'https://support.activision.com/black-ops-7/articles/pc-system-requirements-for-black-ops-7',
      },
      {
        title: 'NVIDIA — Black Ops 7 Game Ready support',
        url: 'https://www.nvidia.com/en-us/geforce/news/gfecnt/202511/call-of-duty-black-ops-7-geforce-game-ready-driver/',
      },
    ],
  },
  {
    id: 'counter-strike-2-display-review',
    game: 'Counter-Strike 2',
    platform: 'Windows PC · Steam',
    status: 'VERIFIED_GUIDANCE',
    lastReviewed: '2026-08-25',
    objective: 'Verify refresh-rate, adaptive-sync, and latency settings using Valve’s current support guidance.',
    applicability: 'Adaptive sync and Reflex guidance depends on the display and GPU. Dialed does not create autoexec files or inject undocumented console commands.',
    automation: 'GUIDANCE_ONLY',
    ongoingTesting: 'Confirm the Windows display mode first, restart CS2 after display-sync changes, and compare a repeatable workshop or practice sequence without mixing resolution and sync changes.',
    settings: [
      {
        id: 'refresh-rate',
        label: 'Highest supported refresh rate',
        recommendation: 'Verify that Windows and CS2 are using the highest refresh rate the display reliably supports.',
        rationale: 'Valve states that higher supported refresh rates produce smoother motion and recommends checking the actual Windows display mode.',
        tradeoff: 'Higher refresh modes may restrict resolution, color depth, or link stability on some display connections.',
        verification: 'Check Advanced display settings, restart CS2, and confirm the active mode rather than assuming the monitor’s advertised maximum is in use.',
      },
      {
        id: 'adaptive-sync',
        label: 'G-SYNC or FreeSync',
        recommendation: 'Enable the display’s supported adaptive-sync technology when available and stable on the chosen display mode.',
        rationale: 'Valve recommends G-SYNC or FreeSync where supported to match display refresh to delivered frame rate.',
        tradeoff: 'Some systems can show glitches in non-fullscreen windowed modes; unsupported combinations may add troubleshooting complexity.',
        verification: 'Restart the game, verify the display indicator if available, and test below and near the refresh ceiling.',
      },
      {
        id: 'gsync-vsync-reflex',
        label: 'G-SYNC, V-Sync, and Reflex combination',
        recommendation: 'When using G-SYNC on a supported NVIDIA setup, review Valve’s recommendation to pair it with V-Sync and NVIDIA Reflex instead of applying a generic V-Sync-off recipe.',
        rationale: 'Valve’s CS2 guidance explicitly describes this combination and its frame-delivery tradeoff.',
        tradeoff: 'Waiting for frame delivery can affect latency differently depending on whether frame rate stays within the adaptive-sync range.',
        verification: 'Use the same frame cap and scenario, then compare tearing, latency feel, and frame-time stability before retaining the combination.',
      },
    ],
    sources: [
      {
        title: 'Steam Support — CS2 video settings recommendations',
        url: 'https://help.steampowered.com/en/faqs/view/418E-7A04-B0DA-9032',
      },
      {
        title: 'Steam Support — Troubleshooting game performance',
        url: 'https://help.steampowered.com/en/faqs/view/5B03-A517-D747-9421',
      },
    ],
  },
  {
    id: 'valorant-pc-performance-review',
    game: 'VALORANT',
    platform: 'Windows PC',
    status: 'VERIFIED_GUIDANCE',
    lastReviewed: '2026-08-25',
    objective: 'Low-latency settings review that respects CPU bottlenecks and Riot Vanguard boundaries.',
    applicability: 'VALORANT is often CPU-limited on mid-to-high-end systems, so reducing every graphics option may not improve frame rate. No game file, launcher flag, or Vanguard-protected state is written.',
    automation: 'GUIDANCE_ONLY',
    ongoingTesting: 'Use a repeatable practice-range sequence, record CPU/GPU utilization and low-percentile frame times, and compare one change at a time with Reflex or Anti-Lag state noted.',
    settings: [
      {
        id: 'bottleneck-first',
        label: 'Identify the bottleneck first',
        recommendation: 'Check whether the system is CPU- or GPU-limited before applying an all-low profile.',
        rationale: 'Riot explains that many mid-to-high-end systems are CPU-bound, where lowering graphics settings may not improve performance.',
        tradeoff: 'Diagnosis takes longer than applying a preset, but avoids discarding visual quality without measurable benefit.',
        verification: 'Compare GPU utilization and frame times in the same practice sequence before and after a single quality change.',
      },
      {
        id: 'latency-feature',
        label: 'Reflex or supported Anti-Lag',
        recommendation: 'Use the in-game low-latency option supported by the installed GPU and current driver, then measure instead of stacking driver overrides.',
        rationale: 'Riot’s performance notes identify NVIDIA Reflex and AMD Anti-Lag as supported latency paths in applicable configurations.',
        tradeoff: 'Availability is hardware- and driver-dependent, and combining overlapping latency controls can make attribution difficult.',
        verification: 'Keep driver overrides at their prior state, enable only the in-game option, and compare the same scene and frame cap.',
      },
      {
        id: 'multithreaded-rendering',
        label: 'Multithreaded rendering',
        recommendation: 'Keep multithreaded rendering enabled on a supported multi-core system unless repeatable evidence shows a compatibility problem.',
        rationale: 'Riot documents ongoing CPU-performance work and specifically references multithreaded rendering in its input-latency behavior.',
        tradeoff: 'Older or unusual systems can behave differently; this is not proof of a universal FPS increase.',
        verification: 'Restart if required and compare CPU utilization plus low-percentile frame times in the same practice sequence.',
      },
    ],
    sources: [
      {
        title: 'Riot Games — Ask VALORANT: performance and CPU limits',
        url: 'https://playvalorant.com/en-us/news/dev/ask-valorant-may-31/',
      },
      {
        title: 'Riot Games — VALORANT patch 6.04 performance notes',
        url: 'https://playvalorant.com/en-us/news/game-updates/valorant-patch-notes-6-04/',
      },
      {
        title: 'Riot Games — VALORANT patch 3.05 Reflex notes',
        url: 'https://playvalorant.com/en-us/news/game-updates/valorant-patch-notes-3-05/',
      },
    ],
  },
  {
    id: 'battlefield-6-pc-performance-review',
    game: 'Battlefield 6',
    platform: 'Windows PC',
    status: 'VERIFIED_GUIDANCE',
    lastReviewed: '2026-08-25',
    objective: 'Competitive visibility and frame-rate review using EA’s current Battlefield 6 graphics guidance.',
    applicability: 'The best balance depends on GPU, resolution, upscaling support, map, player count, and visual preference. Dialed does not overwrite PROFSAVE files.',
    automation: 'GUIDANCE_ONLY',
    ongoingTesting: 'Use the same map segment or practice condition, preserve the prior preset, and compare at least three runs before lowering another setting group.',
    settings: [
      {
        id: 'less-noticeable-quality',
        label: 'Less-noticeable quality settings',
        recommendation: 'Begin by lowering undergrowth, effects, volumetric, lighting, local-light/shadow, sun-shadow, and post-process quality.',
        rationale: 'EA identifies these as starting points for improving FPS with less noticeable visual impact.',
        tradeoff: 'Scene richness, lighting, effects, and shadow definition are reduced.',
        verification: 'Compare the same busy scene and raise back any option whose visual loss exceeds its measured frame-time benefit.',
      },
      {
        id: 'motion-clarity',
        label: 'Motion blur and camera shake',
        recommendation: 'For competitive clarity, try reducing world motion blur, weapon motion blur, and camera shake as low as comfortable.',
        rationale: 'EA recommends reducing these camera effects when they interfere with visibility.',
        tradeoff: 'The presentation can feel less cinematic and personal comfort varies.',
        verification: 'Test rapid movement and recoil-heavy scenes, retaining the lowest comfortable value rather than assuming zero is universal.',
      },
      {
        id: 'screen-space-reflections',
        label: 'Screen-space reflections',
        recommendation: 'Consider disabling screen-space reflections when visibility through reflective water or building interiors matters more than reflection quality.',
        rationale: 'EA notes that some players find targets easier to see with this option off.',
        tradeoff: 'Reflections and environmental realism are reduced; the performance effect depends on the scene and GPU.',
        verification: 'Compare identical reflective scenes for visibility and frame time before retaining the change.',
      },
    ],
    sources: [
      {
        title: 'EA Help — Battlefield 6 PC graphics settings guide',
        url: 'https://help.ea.com/en/articles/battlefield/battlefield-6/pc-and-controller-settings-guide/',
      },
    ],
  },
  {
    id: 'rocket-league-pc-performance-review',
    game: 'Rocket League',
    platform: 'Windows PC · Epic Games / Steam',
    status: 'VERIFIED_GUIDANCE',
    lastReviewed: '2026-08-26',
    objective: 'Stable frame pacing and intentional visual-quality tradeoffs using Rocket League’s supported Video menu.',
    applicability: 'Use the performance options when frame-rate drops are the demonstrated problem. This guide is manual. The separate candidate profile can preview two existing TASystemSettings.ini graphics keys, but game acceptance remains unverified. No launcher arguments are added.',
    automation: 'GUIDANCE_ONLY',
    ongoingTesting: 'Restart Rocket League after the change, repeat the same training sequence, and compare the prior state with one setting group at a time. Keep the prior value when a lower setting does not produce a repeatable pacing improvement.',
    settings: [
      {
        id: 'display-aware-fps-limit',
        label: 'Display-aware FPS limit',
        recommendation: 'Begin with an in-game FPS option that matches the monitor’s active refresh rate, then test a different intentional cap only when latency, tearing, thermals, or pacing justify it.',
        rationale: 'Rocket League Support recommends matching the FPS setting to the monitor refresh rate so the system is not doing unnecessary work.',
        tradeoff: 'A refresh-matched cap is a support baseline, not a universal competitive optimum; lower caps can save power and higher supported caps can affect latency and heat.',
        verification: 'Confirm the active Windows refresh rate, restart the game, and compare frame-time consistency and input feel in the same training sequence.',
      },
      {
        id: 'render-quality-performance',
        label: 'Render and world detail',
        recommendation: 'When GPU load or frame-rate drops are the problem, test Render Quality, Render Detail, World Detail, and Particle Detail at their Performance-oriented values.',
        rationale: 'Epic’s Rocket League support article identifies these built-in values as the supported path for lowering graphics load.',
        tradeoff: 'World, particle, and render fidelity are reduced, and a CPU-limited system may show little or no gain.',
        verification: 'Change this group without also changing resolution or the frame cap, then compare at least three matched runs.',
      },
      {
        id: 'anti-aliasing-performance',
        label: 'Anti-aliasing',
        recommendation: 'Try FXAA Low or Off only when performance is the priority and the resulting edge shimmer is acceptable.',
        rationale: 'Rocket League Support lists FXAA Low or Off among its in-game performance troubleshooting settings.',
        tradeoff: 'Reduced anti-aliasing can make edges and distant field markings shimmer or look rough.',
        verification: 'Compare motion clarity and frame time in the same arena, then restore the prior setting if the visual cost outweighs the measured difference.',
      },
    ],
    sources: [
      {
        title: 'Rocket League Support — Adjust in-game video settings',
        url: 'https://www.epicgames.com/help/c-202300000001748/a202300000010466?lang=en-US',
      },
      {
        title: 'Rocket League Support — Change FPS settings',
        url: 'https://www.epicgames.com/help/c-202300000001622/c-202300000001682/a202300000015632?lang=en-US',
      },
    ],
  },
  {
    id: 'league-of-legends-pc-performance-review',
    game: 'League of Legends',
    platform: 'Windows PC · Riot Client',
    status: 'VERIFIED_GUIDANCE',
    lastReviewed: '2026-08-26',
    objective: 'Troubleshoot low frame rate with reversible in-game changes and a controlled custom-match comparison.',
    applicability: 'Riot presents low video settings as a troubleshooting starting point with an explicit visual-quality cost. Dialed does not overwrite game.cfg or PersistedSettings.json and does not change Windows exploit-protection settings.',
    automation: 'GUIDANCE_ONLY',
    ongoingTesting: 'Use a custom match with bots or no other players, keep the camera path and scene comparable, and change one group at a time. Re-test after major patches because workload behavior can change.',
    settings: [
      {
        id: 'desktop-resolution-baseline',
        label: 'Resolution baseline',
        recommendation: 'Start troubleshooting at the desktop’s active resolution so image scale is known; lower resolution only when GPU load is demonstrated and reduced clarity is acceptable.',
        rationale: 'Riot’s low-FPS troubleshooting baseline uses the desktop resolution and directs players to the in-game Video menu first.',
        tradeoff: 'Lower resolution can reduce GPU load but makes the interface and battlefield less clear; native resolution can remain too demanding on older GPUs.',
        verification: 'Record the active resolution and repeat the same custom-match sequence while watching frame-rate stability.',
      },
      {
        id: 'quality-and-shadows',
        label: 'Character, environment, effects, and shadows',
        recommendation: 'For a low-FPS diagnosis, try very-low character, environment, and effects quality with shadows off, then raise back the options whose visual benefit exceeds their measured cost.',
        rationale: 'Riot lists these values as a low-performance troubleshooting starting point and warns that lower graphics trade quality for speed.',
        tradeoff: 'Character detail, environment detail, effects, and shadow information are reduced; the gain can be small on a CPU-limited system.',
        verification: 'Test in a custom match before using the change in a live game and compare at least three similar passes.',
      },
      {
        id: 'cap-vsync-aa',
        label: 'Frame cap, V-Sync, and anti-aliasing',
        recommendation: 'Use Riot’s 60 FPS cap with V-Sync and anti-aliasing off as a troubleshooting baseline—not a universal competitive preset—then deliberately test the cap and sync state appropriate to the display.',
        rationale: 'Riot includes those values in its low-FPS diagnostic starting point, which helps isolate load before tuning for a higher-refresh display.',
        tradeoff: 'A 60 FPS cap can add latency or feel less smooth on a high-refresh display; disabling V-Sync can introduce tearing and disabling anti-aliasing reduces edge quality.',
        verification: 'Once stability is established, test one cap or sync change at a time in the same custom match and retain only repeatable improvements.',
      },
    ],
    sources: [
      {
        title: 'Riot Games Support — Low frame rate (FPS) troubleshooting',
        url: 'https://support.riotgames.com/en-us/league-of-legends/performance/low-frame-rate-fps-troubleshooting',
      },
    ],
  },
  {
    id: 'overwatch-2-pc-performance-review',
    game: 'Overwatch 2',
    platform: 'Windows PC · Battle.net / Steam',
    status: 'VERIFIED_GUIDANCE',
    lastReviewed: '2026-08-26',
    objective: 'Separate graphics load, hardware pressure, and network symptoms using Overwatch’s supported diagnostics.',
    applicability: 'Blizzard frames these controls as troubleshooting steps, not universal competitive settings. Dialed does not write Settings_v0.ini, modify Battle.net, or automate driver overrides.',
    automation: 'GUIDANCE_ONLY',
    ongoingTesting: 'Use the same practice-range sequence, display the game’s own performance statistics, and revert a change when it does not improve the relevant FPS, VRAM, temperature, or frame-processing evidence.',
    settings: [
      {
        id: 'vsync-diagnostic',
        label: 'V-Sync troubleshooting test',
        recommendation: 'If FPS is unexpectedly poor, test V-Sync off from Options > Video, but turn it back on when performance does not improve or tearing and pacing become worse.',
        rationale: 'Blizzard’s current Overwatch 2 performance troubleshooting explicitly recommends this reversible diagnostic sequence.',
        tradeoff: 'Disabling V-Sync can introduce visible tearing and may increase GPU load; it is not a blanket latency guarantee.',
        verification: 'Compare the same practice-range movement with the same frame cap and restore V-Sync when the evidence is neutral or adverse.',
      },
      {
        id: 'in-game-performance-stats',
        label: 'Use the built-in FPS, temperature, and VRAM readouts',
        recommendation: 'Enable Overwatch’s performance information before lowering multiple settings so the bottleneck hypothesis is grounded in the game’s own FPS, GPU temperature, and VRAM signals.',
        rationale: 'Blizzard documents these readouts and explains that low FPS is system-performance related while near-capacity VRAM can accompany crashes or lockups.',
        tradeoff: 'The overlay is diagnostic, not a benchmark, and temperature limits must come from the hardware manufacturer.',
        verification: 'Capture the same scene before and after one setting change and record FPS, temperature, and VRAM together rather than judging by feel alone.',
      },
      {
        id: 'reset-defaults-recovery',
        label: 'Reset graphics defaults as a recovery baseline',
        recommendation: 'When accumulated changes make the result unclear, use Overwatch’s Reset All Defaults option and rebuild the comparison one setting at a time.',
        rationale: 'Blizzard lists the in-game default reset as the final graphics troubleshooting baseline after simpler checks.',
        tradeoff: 'Resetting removes personalized graphics choices and may not resolve driver, thermal, or hardware-limit problems.',
        verification: 'Record the prior values first, reset, restart when appropriate, and confirm whether the original symptom remains before adding custom settings back.',
      },
    ],
    sources: [
      {
        title: 'Blizzard Support — Overwatch 2 technical troubleshooting',
        url: 'https://us.support.blizzard.com/en/help/article/361234',
      },
      {
        title: 'Blizzard Support — Diagnosing Overwatch network problems',
        url: 'https://us.support.blizzard.com/article/000037007',
      },
    ],
  },
]);

function listGameSettingsGuides() {
  return JSON.parse(JSON.stringify(GAME_SETTINGS_GUIDES));
}

module.exports = {
  GAME_SETTINGS_GUIDES,
  listGameSettingsGuides,
};
