function deepFreeze(value) {
  if (!value || typeof value !== 'object' || Object.isFrozen(value)) return value;
  Object.freeze(value);
  for (const child of Object.values(value)) deepFreeze(child);
  return value;
}

// What a row is for. A reader scanning for "less input lag" or "see enemies better" filters on
// this, and it keeps each row honest about its purpose: most rows trade looks for frame rate,
// some only change what is visible, and none promises a number.
const HELPS = Object.freeze(['FRAME_RATE', 'LATENCY', 'VISIBILITY', 'SMOOTHNESS', 'STABILITY', 'AIM', 'AWARENESS']);

// Who said it. The owner's rule (2026-10-01): the game's maker, a GPU maker, or a publication
// that tested or observed it, credited on the row. No community wikis or forum advice.
const SOURCE_KINDS = Object.freeze(['GAME_MAKER', 'GPU_MAKER', 'TESTED', 'PRESS']);

const NVIDIA_LATENCY_GUIDE = { title: 'NVIDIA — A guide to better system latency', url: 'https://www.nvidia.com/en-us/geforce/guides/gfecnt/202010/system-latency-optimization-guide/', kind: 'GPU_MAKER' };
const NVIDIA_REFLEX_BOOST = { title: 'NVIDIA — Counter-Strike 2 with Reflex (Boost tradeoff)', url: 'https://www.nvidia.com/en-us/geforce/news/counter-strike-2-released-featuring-nvidia-reflex/', kind: 'GPU_MAKER' };

// The same two questions come up in every game, and NVIDIA's measured advice answers both.
function syncRow(source) {
  return {
    id: 'sync-and-cap', label: 'V-Sync and frame cap', helps: 'SMOOTHNESS', source,
    value: 'G-SYNC or FreeSync screen: V-Sync on in the driver, with Reflex. Otherwise V-Sync off.',
    why: 'With adaptive sync this caps just under your refresh rate: no tearing, low latency.',
    detail: 'NVIDIA measured uncapped with Reflex as slightly lower latency still, at the cost of tearing. Driver V-Sync only applies in fullscreen; in windowed mode use the game\'s own V-Sync.',
  };
}
function reflexRow(source, boostSource = source) {
  return {
    id: 'reflex', label: 'NVIDIA Reflex', helps: 'LATENCY', source,
    value: 'On. On + Boost only if you put latency before frame rate.',
    why: 'Stops the CPU queuing frames ahead of the GPU; matters most when the GPU is the limit.',
    detail: 'NVIDIA cards only. NVIDIA says Boost uses more power and gives a slightly lower frame rate.',
    detailSource: boostSource,
  };
}

const GAME_SETTINGS_GUIDES = deepFreeze([
  {
    id: 'fortnite-pc-performance-review',
    game: 'Fortnite',
    platform: 'Windows PC · Epic Games',
    status: 'VERIFIED_GUIDANCE',
    lastReviewed: '2026-10-01',
    summary: 'Epic\'s own 2026 competitive setup: Performance mode, near view distance, low meshes and textures, Reflex with Boost.',
    automation: 'GUIDANCE_ONLY',
    howToTest: 'Turn on Show FPS (Video > Advanced Graphics), then repeat the same route in a Creative island after each change.',
    boundaries: [],
    settings: [
      { id: 'rendering-mode', label: 'Rendering Mode', value: 'Performance', helps: 'FRAME_RATE', source: 0,
        why: 'A DirectX 12 mode that turns off most rendering features to cut memory use and CPU and GPU load.',
        detail: 'Looks plainer and needs a restart. Ray tracing is not available in it.', detailSource: 1 },
      { id: 'view-distance', label: 'View Distance', value: 'Near', helps: 'FRAME_RATE', source: 0,
        why: 'Epic says players stay clearly visible at Near; only scenery is trimmed.' },
      { id: 'textures-meshes', label: 'Textures and Meshes', value: 'Low', helps: 'FRAME_RATE', source: 0,
        why: 'Less detailed objects and textures free GPU memory and load.' },
      { id: 'three-d-resolution', label: '3D Resolution', value: '100%, then down 10% at a time if short', helps: 'VISIBILITY', source: 0,
        why: 'Keeps the image sharp; lower it only when you still need frames.' },
      { ...reflexRow(0, 2), why: 'Epic recommends On + Boost for competitive play; it cuts GPU queueing.' },
      { id: 'frame-rate-limit', label: 'Frame Rate Limit', value: 'Unlimited, or your refresh rate if you see tearing', helps: 'LATENCY', source: 0,
        why: 'More frames reach the screen sooner; a cap at refresh trades a little latency for no tearing.' },
      { id: 'window-vsync', label: 'Window Mode and V-Sync', value: 'Fullscreen, V-Sync off', helps: 'LATENCY', source: 0,
        why: 'Both remove input lag; pair with G-SYNC or FreeSync to avoid tearing.' },
      { id: 'sound', label: '3D Headphones and Visualize Sound Effects', value: 'On', helps: 'AWARENESS', source: 0,
        why: 'Directional audio, and an on-screen ring showing where loud sounds come from.' },
    ],
    sources: [
      { title: 'Epic Games — Fortnite on PC: best settings for competitive play in 2026', url: 'https://store.epicgames.com/news/fortnite-on-pc-best-settings-for-competitive-play-in-2026', kind: 'GAME_MAKER' },
      { title: 'Epic Games — Enable Performance mode in Fortnite', url: 'https://www.epicgames.com/help/c-202300000001636/c-202300000001719/how-do-i-enable-performance-mode-in-fortnite-a202300000013270', kind: 'GAME_MAKER' },
      NVIDIA_REFLEX_BOOST,
    ],
  },
  {
    id: 'apex-legends-pc-performance-review',
    game: 'Apex Legends',
    platform: 'Windows PC · EA app / Steam',
    status: 'VERIFIED_GUIDANCE',
    lastReviewed: '2026-10-01',
    summary: 'EA\'s full competitive table. EA says any setting it leaves out does not affect performance.',
    automation: 'GUIDANCE_ONLY',
    howToTest: 'Show FPS in game, then run the same Firing Range route after each group of changes.',
    boundaries: [],
    settings: [
      { id: 'texture-streaming-budget', label: 'Texture Streaming Budget', value: 'Low or Medium, within your VRAM', helps: 'STABILITY', source: 0,
        why: 'Sets how much video memory textures may use; over your card\'s memory it hitches.',
        detail: 'Lower is blurrier up close.' },
      { id: 'shadows-lighting', label: 'Ambient Occlusion, Volumetric Lighting, Dynamic Spot Shadows', value: 'Disabled', helps: 'FRAME_RATE', source: 0,
        why: 'EA\'s competitive pick: these are expensive and add little you need to see.' },
      { id: 'shadow-detail', label: 'Sun Shadow Coverage and Detail, Spot Shadow Detail', value: 'Low', helps: 'FRAME_RATE', source: 0,
        why: 'Cheaper shadows with the same shapes.' },
      { id: 'model-effects', label: 'Model Detail, Effects Detail, Ragdolls, Impact Marks', value: 'Low (Impact Marks Low or Disabled)', helps: 'FRAME_RATE', source: 0,
        why: 'Fewer effects and less clutter in busy fights.' },
      { id: 'aa-filtering', label: 'Anti-aliasing and Texture Filtering', value: 'None, and Bilinear', helps: 'FRAME_RATE', source: 0,
        why: 'EA\'s competitive values.', detail: 'Edges look rougher; raise Adaptive Supersampling if it looks too harsh.' },
      { id: 'adaptive-resolution', label: 'Adaptive Resolution FPS Target', value: '0 (off)', helps: 'VISIBILITY', source: 0,
        why: 'Otherwise the game drops resolution on its own; EA says leave it off unless frame rate dips often.' },
      { ...reflexRow(0, 1), why: 'EA recommends it on NVIDIA cards.' },
      { id: 'vsync', label: 'V-Sync', value: 'Disabled, unless you see tearing', helps: 'LATENCY', source: 0,
        why: 'Removes the wait for the display.' },
      { id: 'aim', label: 'ADS Sensitivity Multiplier and Mouse Acceleration', value: '1.0, and Off', helps: 'AIM', source: 0,
        why: 'The same hand movement turns the same amount every time.' },
      { id: 'fov-shake', label: 'Field of View and Sprint View Shake', value: '90-110, and Minimal', helps: 'VISIBILITY', source: 0,
        why: 'Wider view; less screen movement while sprinting. 110 is common in competitive play.' },
    ],
    sources: [
      { title: 'EA Help — Best settings for Apex Legends on PC', url: 'https://help.ea.com/en/articles/apex-legends/best-settings-pc/', kind: 'GAME_MAKER' },
      NVIDIA_REFLEX_BOOST,
    ],
  },
  {
    id: 'call-of-duty-black-ops-7-performance-review',
    game: 'Call of Duty: Black Ops 7',
    platform: 'Windows PC · Battle.net / Steam / Xbox app',
    status: 'VERIFIED_GUIDANCE',
    lastReviewed: '2026-10-01',
    summary: 'Use the game\'s built-in benchmark to judge each change, keep one upscaler, and size textures to your video memory.',
    automation: 'GUIDANCE_ONLY',
    howToTest: 'Run the in-game Call of Duty PC Benchmark Tool before and after each change; it repeats the same scene every time.',
    boundaries: [
      'Dialed does not copy template files, does not write versioned cod25 files, and does not change launcher arguments, RICOCHET, TPM, Secure Boot or account state.',
    ],
    settings: [
      { id: 'benchmark-tool', label: 'Call of Duty PC Benchmark Tool', value: 'Run it before and after each change', helps: 'STABILITY', source: 1,
        why: 'Built into the game; a fixed scene gives a fair comparison, unlike a live match.' },
      { id: 'render-resolution', label: 'Render Resolution', value: '100% at your monitor\'s native resolution', helps: 'VISIBILITY', source: 0,
        why: 'Start sharp; let an upscaler find frames instead of lowering this.' },
      { id: 'one-upscaler', label: 'Upscaling', value: 'One path only: DLSS, FSR or XeSS at Quality', helps: 'FRAME_RATE', source: 1,
        why: 'Renders fewer pixels and rebuilds the image.',
        detail: 'Frame generation raises the counter without making aim respond sooner; judge it separately.' },
      { id: 'texture-vram', label: 'Texture Resolution', value: 'Fit your video memory', helps: 'STABILITY', source: 0,
        why: 'Activision lists 8 GB for High at 60 fps and 16 GB for its competitive and 4K tier; over budget it stutters.' },
      { id: 'cap-sync-latency', label: 'Frame cap and Reflex', value: 'A cap chosen for your display, Reflex on', helps: 'LATENCY', source: 2,
        why: 'Pick the cap instead of treating Off, 300 or 600 FPS as universal; every PC and display differs.' },
      { id: 'effects-groups', label: 'Motion blur, depth of field, particles, shadows, reflections, weather', value: 'Lower one group at a time', helps: 'FRAME_RATE', source: 0,
        why: 'Black Ops 7 splits these into separate settings, so keep only the cuts the benchmark shows matter.' },
      { id: 'input-audio-boundary', label: 'Sensitivity, polling rate and audio mix', value: 'Your own', helps: 'AIM', source: null,
        why: 'Do not copy another player’s sensitivity, polling rate or audio mix; they are preferences, not performance.' },
    ],
    sources: [
      { title: 'Call of Duty — Black Ops 7 on PC (requirements and tiers)', url: 'https://www.callofduty.com/blackops7/pc', kind: 'GAME_MAKER' },
      { title: 'Call of Duty — Black Ops 7 PC launch: benchmark tool and features', url: 'https://www.callofduty.com/blog/2025/11/call-of-duty-black-ops-7-pc-trailer-specs-preloading-handheld-systems', kind: 'GAME_MAKER' },
      { title: 'NVIDIA — Black Ops 7 Game Ready support (Reflex, DLSS)', url: 'https://www.nvidia.com/en-us/geforce/news/gfecnt/202511/call-of-duty-black-ops-7-geforce-game-ready-driver/', kind: 'GPU_MAKER' },
    ],
  },
  {
    id: 'counter-strike-2-display-review',
    game: 'Counter-Strike 2',
    platform: 'Windows PC · Steam',
    status: 'VERIFIED_GUIDANCE',
    lastReviewed: '2026-10-01',
    summary: 'Valve\'s own setup: highest refresh, G-SYNC with V-Sync and Reflex together, and Boost Player Contrast on.',
    automation: 'GUIDANCE_ONLY',
    howToTest: 'Restart CS2 after any display or sync change, then compare the same workshop map run.',
    boundaries: ['Dialed does not create autoexec files or add console commands.'],
    settings: [
      { id: 'refresh-rate', label: 'Refresh rate', value: 'Your monitor\'s highest, and check Windows is really using it', helps: 'SMOOTHNESS', source: 0,
        why: 'Windowed modes use the desktop\'s mode, which is often not the monitor\'s fastest.' },
      { id: 'adaptive-sync', label: 'G-SYNC or FreeSync', value: 'On, in the graphics driver', helps: 'SMOOTHNESS', source: 0,
        why: 'The screen follows the frame rate, so dips do not judder; Valve says it never hurts.',
        detail: 'Valve notes G-SYNC can glitch in non-fullscreen windowed mode on some systems.' },
      { id: 'gsync-vsync-reflex', label: 'With G-SYNC: V-Sync and Reflex', value: 'Both on (CS2 offers this when it starts)', helps: 'SMOOTHNESS', source: 0,
        why: 'Valve calls it usually the smoothest and lowest-latency combination; it caps just under refresh.',
        detail: 'NVIDIA measured uncapped Reflex as slightly lower latency, with tearing.', detailSource: 3 },
      { id: 'boost-player-contrast', label: 'Boost Player Contrast', value: 'Enabled', helps: 'VISIBILITY', source: 1,
        why: 'A filter that makes players stand out from the background, especially at a distance.' },
      { ...reflexRow(2) },
      { id: 'anti-lag-2', label: 'AMD Anti-Lag 2 (Radeon)', value: 'On in the game; never a driver-forced Anti-Lag+', helps: 'LATENCY', source: 4,
        why: 'The in-game version is supported. The older driver-level Anti-Lag+ injected code and games treated it as cheating.' },
    ],
    sources: [
      { title: 'Valve — CS2 video settings recommendations', url: 'https://help.steampowered.com/en/faqs/view/418E-7A04-B0DA-9032', kind: 'GAME_MAKER' },
      { title: 'Valve — Enemy Spotted (Boost Player Contrast)', url: 'https://blog.counter-strike.net/index.php/2020/06/30428/', kind: 'GAME_MAKER' },
      NVIDIA_REFLEX_BOOST,
      NVIDIA_LATENCY_GUIDE,
      { title: 'Tom\'s Hardware — AMD Anti-Lag 2 in Counter-Strike 2', url: 'https://www.tomshardware.com/pc-components/gpu-drivers/amd-introduces-radeon-anti-lag-2-with-full-integration-for-counter-strike-2-the-nvidia-reflex-alternative-shouldnt-trigger-cheating-bans-this-time', kind: 'PRESS' },
    ],
  },
  {
    id: 'valorant-pc-performance-review',
    game: 'VALORANT',
    platform: 'Windows PC · Riot Client',
    status: 'VERIFIED_GUIDANCE',
    lastReviewed: '2026-10-01',
    summary: 'VALORANT is often limited by the processor, so lowering graphics may change nothing. Fix latency first.',
    automation: 'GUIDANCE_ONLY',
    howToTest: 'Repeat the same Range routine and compare CPU and GPU load before and after one change.',
    boundaries: ['Dialed writes no game file, launcher flag or Vanguard-protected state.'],
    settings: [
      { id: 'bottleneck-first', label: 'Before lowering graphics', value: 'Check whether the CPU or the GPU is the limit', helps: 'FRAME_RATE', source: 1,
        why: 'Riot says many mid-to-high-end PCs are CPU-bound, where lower graphics does not raise frame rate.' },
      { id: 'multithreaded-rendering', label: 'Multithreaded Rendering', value: 'On with 8+ CPU threads, 8 GB RAM and 2 GB VRAM', helps: 'FRAME_RATE', source: 0,
        why: 'Riot: can improve CPU performance and graphics quality on PCs that meet those specs.' },
      { ...reflexRow(2, 5), why: 'Riot added Reflex to cut the time from click to screen.' },
      { id: 'raw-input-buffer', label: 'Raw Input Buffer', value: 'Nothing to do: always on since patch 11.06', helps: 'AIM', source: 3,
        why: 'Riot removed the toggle and keeps it on because it performs better; older guides still mention it.' },
      syncRow(4),
    ],
    sources: [
      { title: 'Riot Games — Multithreaded Rendering', url: 'https://support.riotgames.com/en-us/valorant/support-tools/multithreaded-rendering', kind: 'GAME_MAKER' },
      { title: 'Riot Games — Ask VALORANT: performance and CPU limits', url: 'https://playvalorant.com/en-us/news/dev/ask-valorant-may-31/', kind: 'GAME_MAKER' },
      { title: 'Riot Games — VALORANT patch 3.05 (Reflex)', url: 'https://playvalorant.com/en-us/news/game-updates/valorant-patch-notes-3-05/', kind: 'GAME_MAKER' },
      { title: 'Riot Games — VALORANT patch 11.06 (Raw Input Buffer always on)', url: 'https://playvalorant.com/en-us/news/game-updates/valorant-patch-notes-11-06/', kind: 'GAME_MAKER' },
      NVIDIA_LATENCY_GUIDE,
      NVIDIA_REFLEX_BOOST,
    ],
  },
  {
    id: 'battlefield-6-pc-performance-review',
    game: 'Battlefield 6',
    platform: 'Windows PC · EA app / Steam',
    status: 'VERIFIED_GUIDANCE',
    lastReviewed: '2026-10-01',
    summary: 'Start from High, not Overkill: TechSpot found them nearly identical, and Low about 70% faster than Overkill.',
    automation: 'GUIDANCE_ONLY',
    howToTest: 'Turn on the performance overlay and repeat the same Firing Range or Portal map route after each change.',
    boundaries: ['Dialed does not overwrite PROFSAVE files.'],
    settings: [
      { id: 'preset', label: 'Graphics preset', value: 'High; on an 8 GB card, never Overkill', helps: 'FRAME_RATE', source: 1,
        why: 'TechSpot found High almost identical to Overkill, and Overkill too heavy for 8 GB cards.' },
      { id: 'less-noticeable-quality', label: 'Undergrowth, Effects, Volumetric, Lighting, Local Light & Shadow, Sun Shadow, Post Process', value: 'Low', helps: 'FRAME_RATE', source: 0,
        why: 'EA picks these as the ones you notice least.' },
      { id: 'upscaling', label: 'Upscaling', value: 'DLSS or FSR at Quality', helps: 'FRAME_RATE', source: 1,
        why: 'TechSpot measured about 40% more frames than native at Quality.', detail: 'Balanced and Performance add more, with a softer image.' },
      { id: 'screen-space-reflections', label: 'Screen Space Reflections', value: 'Off', helps: 'VISIBILITY', source: 0,
        why: 'EA: some players find enemies easier to see in buildings and through water.' },
      { id: 'motion-clarity', label: 'Motion blur, camera shake, chromatic aberration, vignette, film grain', value: 'Lowest, or Off', helps: 'VISIBILITY', source: 0,
        why: 'EA: keeps them from getting in the way of your view.' },
      { id: 'fov', label: 'Field of View and Weapon Field of View', value: '110, and Wide', helps: 'VISIBILITY', source: 0,
        why: 'EA\'s suggested start: more of the battlefield in view.' },
      { id: 'hud-motion', label: 'Soldier and Vehicle HUD Motion', value: 'Off', helps: 'VISIBILITY', source: 0,
        why: 'The HUD stays still while you move.' },
      { id: 'zoom-coefficient', label: 'Zoom Sensitivity Coefficient', value: 'EA starts at 178; lower it if zoomed aim feels fast', helps: 'AIM', source: 0,
        why: 'Higher values add sensitivity while aiming down sights. A preference, not performance.' },
      { id: 'vsync', label: 'Vertical Sync', value: 'Off', helps: 'LATENCY', source: 0, why: 'EA: avoids lag.' },
    ],
    sources: [
      { title: 'EA Help — Battlefield 6 PC and controller settings guide', url: 'https://help.ea.com/en/articles/battlefield/battlefield-6/pc-and-controller-settings-guide/', kind: 'GAME_MAKER' },
      { title: 'TechSpot — Battlefield 6 benchmark: 43 GPUs tested', url: 'https://www.techspot.com/review/3042-battlefield-6-benchmark/', kind: 'TESTED' },
    ],
  },
  {
    id: 'rocket-league-pc-performance-review',
    game: 'Rocket League',
    platform: 'Windows PC · Epic Games / Steam',
    status: 'VERIFIED_GUIDANCE',
    lastReviewed: '2026-10-01',
    summary: 'Psyonix\'s performance values for every quality setting, and a frame cap matched to your monitor.',
    automation: 'GUIDANCE_ONLY',
    howToTest: 'Restart the game, then repeat the same Free Play routine after each change.',
    boundaries: ['This guide changes nothing. The separate Rocket League profile only turns off motion blur and dynamic shadows.'],
    settings: [
      { id: 'render-quality', label: 'Render Quality and Render Detail', value: 'Performance', helps: 'FRAME_RATE', source: 0,
        why: 'Epic\'s support values for lowering graphics load.' },
      { id: 'world-particle', label: 'World Detail and Particle Detail', value: 'Performance', helps: 'FRAME_RATE', source: 0,
        why: 'Epic\'s support values for less arena and effect detail.' },
      { id: 'texture-detail', label: 'Texture Detail', value: 'High Performance', helps: 'FRAME_RATE', source: 0,
        why: 'Epic\'s performance value.' },
      { id: 'anti-aliasing', label: 'Anti-Aliasing', value: 'FXAA Low, or Off', helps: 'FRAME_RATE', source: 0,
        why: 'Epic\'s performance value.', detail: 'Edges and field lines can shimmer.' },
      { id: 'display-aware-fps-limit', label: 'Frames Per Second', value: 'Your monitor\'s refresh rate', helps: 'SMOOTHNESS', source: 1,
        why: 'Epic: smoother play, and the PC does no more work than the screen can show.' },
      syncRow(2),
    ],
    sources: [
      { title: 'Rocket League Support — Adjust in-game video settings', url: 'https://www.epicgames.com/help/rocket-league-c-37599050/gameplay-c-32343914/how-do-i-adjust-the-in-game-video-settings-in-rocket-league-a20386380', kind: 'GAME_MAKER' },
      { title: 'Rocket League Support — Change FPS settings', url: 'https://www.epicgames.com/help/rocket-league-c-37599050/gameplay-c-32343914/how-do-i-change-my-fps-settings-in-rocket-league-a10445751', kind: 'GAME_MAKER' },
      NVIDIA_LATENCY_GUIDE,
    ],
  },
  {
    id: 'league-of-legends-pc-performance-review',
    game: 'League of Legends',
    platform: 'Windows PC · Riot Client',
    status: 'VERIFIED_GUIDANCE',
    lastReviewed: '2026-10-01',
    summary: 'Riot\'s low-frame-rate setup, plus Low Spec Mode for a slow client.',
    automation: 'GUIDANCE_ONLY',
    howToTest: 'Try changes in a custom game first, as Riot suggests, using the same camera path.',
    boundaries: ['Dialed does not overwrite game.cfg or PersistedSettings.json.'],
    settings: [
      { id: 'quality-and-shadows', label: 'Character, Environment and Effects Quality; Shadows', value: 'Very Low; No Shadow', helps: 'FRAME_RATE', source: 0,
        why: 'Riot\'s starting point when frame rate is low.' },
      { id: 'interface-options', label: 'HUD animations, target frame on attack, line missile display, attack range', value: 'Off', helps: 'FRAME_RATE', source: 0,
        why: 'Riot lists these four interface extras as worth turning off.' },
      { id: 'vsync-aa', label: 'Wait for Vertical Sync and Anti-Aliasing', value: 'Off', helps: 'LATENCY', source: 0,
        why: 'Removes the wait for the display and the smoothing cost.' },
      { id: 'cap', label: 'Frame Rate Cap', value: '60 while troubleshooting, then your refresh rate', helps: 'SMOOTHNESS', source: 0,
        why: 'Riot uses 60 to find the problem; on a fast monitor raise it once things are stable.' },
      { id: 'low-spec-mode', label: 'Low Spec Mode (client)', value: 'On if the client itself is slow', helps: 'STABILITY', source: 1,
        why: 'Sets the client\'s own settings to low. Only from the client, outside a game.' },
    ],
    sources: [
      { title: 'Riot Games — Low frame rate (FPS) troubleshooting', url: 'https://support.riotgames.com/en-us/league-of-legends/performance/low-frame-rate-fps-troubleshooting', kind: 'GAME_MAKER' },
      { title: 'Riot Games — Fix My League: first steps (Low Spec Mode)', url: 'https://support.riotgames.com/en-us/league-of-legends/performance/fix-my-league-the-first-steps-to-tech-help', kind: 'GAME_MAKER' },
    ],
  },
  {
    id: 'overwatch-2-pc-performance-review',
    game: 'Overwatch 2',
    platform: 'Windows PC · Battle.net / Steam',
    status: 'VERIFIED_GUIDANCE',
    lastReviewed: '2026-10-01',
    summary: 'Blizzard\'s own explanation of the buffering settings, which trade frame rate for input latency.',
    automation: 'GUIDANCE_ONLY',
    howToTest: 'Turn on the performance stats overlay and repeat the same Practice Range route.',
    boundaries: ['Dialed does not write Settings_v0.ini, change Battle.net, or set driver overrides.'],
    settings: [
      { id: 'reduce-buffering', label: 'Reduce Buffering', value: 'On; Off on a low-end PC', helps: 'LATENCY', source: 0,
        why: 'Blizzard: cuts the input delay from buffering; on a weak PC turning it off gains frames.' },
      { id: 'triple-buffering', label: 'Triple Buffering', value: 'Off, especially below recommended specs', helps: 'FRAME_RATE', source: 0,
        why: 'Blizzard: it adds GPU load; below recommended specs, off performs better.' },
      { id: 'display-mode', label: 'Display Mode', value: 'Full Screen', helps: 'LATENCY', source: 0,
        why: 'Blizzard: borderless is really a window, and full screen can run a little faster on low-end PCs.', detailSource: 2,
        detail: 'NVIDIA still recommends fullscreen over borderless after testing.' },
      { id: 'fps-limit', label: 'Frame Rate limit', value: 'Display-based, or Custom near your refresh rate', helps: 'SMOOTHNESS', source: 0,
        why: 'Blizzard offers Display-based to match your monitor, or a value of your own.' },
      { ...reflexRow(2, 3), why: 'If the menu shows it, NVIDIA recommends it on.' },
      { id: 'in-game-performance-stats', label: 'Performance stats', value: 'On while testing', helps: 'STABILITY', source: 1,
        why: 'Blizzard\'s overlay shows FPS, GPU temperature and video memory together.' },
    ],
    sources: [
      { title: 'Blizzard Support — About Overwatch graphics settings', url: 'https://eu.support.blizzard.com/en/article/101186', kind: 'GAME_MAKER' },
      { title: 'Blizzard Support — Overwatch technical troubleshooting', url: 'https://us.support.blizzard.com/en/help/article/361234', kind: 'GAME_MAKER' },
      NVIDIA_LATENCY_GUIDE,
      NVIDIA_REFLEX_BOOST,
    ],
  },
  {
    id: 'arc-raiders-pc-performance-review',
    game: 'ARC Raiders',
    platform: 'Windows PC · Steam / Epic Games',
    status: 'VERIFIED_GUIDANCE',
    lastReviewed: '2026-10-01',
    summary: 'Foliage changes what you can see, ray-traced lighting is the costly option, and Reflex is supported.',
    automation: 'GUIDANCE_ONLY',
    howToTest: 'The tutorial mission plays the same way every time, which makes it a fair place to compare.',
    boundaries: [],
    settings: [
      { id: 'foliage', label: 'Foliage', value: 'Low', helps: 'VISIBILITY', source: 1,
        why: 'PC Gamer saw Low remove knee-high bushes and small shrubs; the large bushes you hide in stay.' },
      { id: 'rtx-gi', label: 'RTX Global Illumination', value: 'Off, or lower first when frames are short', helps: 'FRAME_RATE', source: 2,
        why: 'PC Games Hardware calls the ray-traced lighting the costly option.' },
      { id: 'upscaler-clarity', label: 'Upscaling', value: 'If DLSS smears particles, compare TSR', helps: 'VISIBILITY', source: 2,
        why: 'PC Games Hardware saw ghosting with DLSS Quality that TSR at native did not show.',
        detail: 'Seen in a 2025 preview build; check it on the current version.' },
      { ...reflexRow(0, 4), why: 'Supported by the game; NVIDIA says it cuts PC latency noticeably.' },
      syncRow(3),
    ],
    sources: [
      { title: 'NVIDIA — ARC Raiders with DLSS 4 and Reflex', url: 'https://www.nvidia.com/en-us/geforce/news/arc-raiders-dlss-4-multi-frame-generation-out-now/', kind: 'GPU_MAKER' },
      { title: 'PC Gamer — ARC Raiders foliage differs by graphics setting', url: 'https://www.pcgamer.com/games/third-person-shooter/psa-look-out-sweaty-pvpers-arc-raiders-foliage-looks-a-little-different-depending-on-your-graphics-settings/', kind: 'PRESS' },
      { title: 'PC Games Hardware — ARC Raiders graphics and performance', url: 'https://www.pcgameshardware.de/Arc-Raiders-Spiel-73530/Specials/Release-Test-Gameplay-UE5-Raytracing-1484964/2/', kind: 'TESTED' },
      NVIDIA_LATENCY_GUIDE,
      NVIDIA_REFLEX_BOOST,
    ],
  },
  {
    id: 'marvel-rivals-pc-performance-review',
    game: 'Marvel Rivals',
    platform: 'Windows PC · Steam / Epic Games',
    status: 'VERIFIED_GUIDANCE',
    lastReviewed: '2026-10-01',
    summary: 'Stutters and crashes are mostly memory: NetEase\'s shader mode is the fix it recommends.',
    automation: 'GUIDANCE_ONLY',
    howToTest: 'Play the same Practice Range route; watch for drops and stutters, not just the average.',
    boundaries: ['NetEase\'s help also suggests turning antivirus off. Dialed does not: leave your protection on.'],
    settings: [
      { id: 'shader-compilation-mode', label: 'Switch Shader Compilation Mode (launcher)', value: 'On with 16 GB RAM or less and drops or crashes', helps: 'STABILITY', source: 0,
        why: 'NetEase: compiles shaders once, after an update, and cuts memory use sharply.',
        detail: 'Some materials look wrong for a few frames, and a short stutter can start a match. With 6 CPU threads or fewer, avoid combining it with FSR 3 Frame Generation.' },
      { id: 'windows-gpu-preference', label: 'Windows graphics preference for Marvel.exe', value: 'High performance', helps: 'FRAME_RATE', source: 1,
        why: 'NetEase: on PCs with two GPUs, makes sure the fast one runs the game.' },
      { id: 'clean-driver', label: 'Graphics driver', value: 'A clean install of the latest', helps: 'STABILITY', source: 1,
        why: 'NetEase\'s first step for frequent stuttering.' },
      { ...reflexRow(2, 4), why: 'NVIDIA lists Marvel Rivals among its Reflex games.' },
      syncRow(3),
    ],
    sources: [
      { title: 'NetEase — Switch Shader Compilation Mode', url: 'https://www.marvelrivals.com/news/20250408/40185_1225743.html', kind: 'GAME_MAKER' },
      { title: 'NetEase — Common technical issues FAQ', url: 'https://www.marvelrivals.com/guide/20241201/41348_1197223.html', kind: 'GAME_MAKER' },
      { title: 'NVIDIA — Marvel Rivals Season 3 with DLSS 4 and Reflex', url: 'https://www.nvidia.com/en-us/geforce/news/marvel-rivals-season-3-dlss-4-multi-frame-generation-reflex/', kind: 'GPU_MAKER' },
      NVIDIA_LATENCY_GUIDE,
      NVIDIA_REFLEX_BOOST,
    ],
  },
  {
    id: 'pubg-battlegrounds-pc-performance-review',
    game: 'PUBG: BATTLEGROUNDS',
    platform: 'Windows PC · Steam',
    status: 'VERIFIED_GUIDANCE',
    lastReviewed: '2026-10-01',
    summary: 'Switch older installs to DirectX 11 Enhanced and keep crash-data collection off.',
    automation: 'GUIDANCE_ONLY',
    howToTest: 'Use the Training map and repeat the same route after each change.',
    boundaries: [],
    settings: [
      { id: 'directx-version', label: 'DirectX Version', value: 'DirectX 11 Enhanced', helps: 'FRAME_RATE', source: 0,
        why: 'KRAFTON: spreads rendering across CPU threads and can raise frame rate. Only new installs get it by default.' },
      { id: 'gpu-crash-data', label: 'Collect GPU Crash Data', value: 'Off, unless support asks for it', helps: 'FRAME_RATE', source: 0,
        why: 'KRAFTON: its extra checks may lower performance; it switches itself off after 7 days.' },
      { id: 'render-scale', label: 'Render Scale', value: '100; 90 with driver sharpening only if you need frames', helps: 'FRAME_RATE', source: 1,
        why: 'NVIDIA\'s 2020 setup for 240 fps used 90 plus Image Sharpening to hide the softer image.',
        detail: 'From 2020; check it against the current game.' },
      syncRow(2),
    ],
    sources: [
      { title: 'KRAFTON — PUBG Update 25.2 patch notes (DirectX 11 Enhanced)', url: 'https://pubg.com/en/news/6616?category=patch_notes', kind: 'GAME_MAKER' },
      { title: 'NVIDIA — PUBG at 144+ FPS (2020)', url: 'https://www.nvidia.com/en-us/geforce/news/pubg-144-and-240-fps-competitive-gaming-guide/', kind: 'GPU_MAKER' },
      NVIDIA_LATENCY_GUIDE,
    ],
  },
]);

function listGameSettingsGuides() {
  return JSON.parse(JSON.stringify(GAME_SETTINGS_GUIDES));
}

module.exports = {
  GAME_SETTINGS_GUIDES,
  HELPS,
  SOURCE_KINDS,
  listGameSettingsGuides,
};
