import type { AuditDeletionMode, AuditDeletionPreview, AuditExportPreview, AuditHistoryState, AuditJournalEntry, AuditJournalRecoveryResult, BenchmarkEvidenceState, BenchmarkImportPreview, CapabilityRecord, DriftReport, GameConfigBackup, GameConfigRestorePreview, GameConfigRestoreResult, GameSettingsGuide, InstalledApplicationInventory, InstalledGameDiscovery, LocalRecommendation, ManageableProcess, NetworkProbeConsentPreview, NetworkProbeEndpoint, NetworkProbeProgress, NetworkProbeResult, NetworkQualityHistoryState, OptionalAppInventory, OptionalAppRemovalPreview, PolicyMutationResult, PresentMonCaptureConsentPreview, PresentMonCaptureEntry, PresentMonCaptureState, PresentMonImportMetadata, PresentMonTarget, PresentMonToolInfo, ReleaseStatus, RuntimeProfileState, SafeOsPolicy, StartupManagementItem, SystemScanSnapshot, TimingExperiment, UpdateCheckResult, UpdateDownloadResult } from './types';

export interface ReportedDisplayInventory {
  collectedAt: string;
  displays: Array<{
    id: number | null;
    label: string;
    refreshRateHz: number | null;
    logicalWidth: number | null;
    logicalHeight: number | null;
    scaleFactor: number | null;
    primary?: boolean;
  }>;
}

declare global {
  interface Window {
    pcOptiNative?: {
      getRuntimeProfile: () => Promise<RuntimeProfileState>;
      listCapabilities: () => Promise<CapabilityRecord[]>;
      scanSystem: () => Promise<SystemScanSnapshot>;
      listInstalledApplications: () => Promise<InstalledApplicationInventory>;
      listOptionalAppCandidates: () => Promise<OptionalAppInventory>;
      previewOptionalAppRemoval: (appId: string) => Promise<OptionalAppRemovalPreview>;
      applyOptionalAppRemoval: (token: string) => Promise<{ success: boolean; entry: AuditJournalEntry; result?: unknown; error?: string }>;
      openWindowsSettings: (pageId: 'game-mode' | 'game-bar' | 'captures' | 'graphics' | 'installed-apps' | 'startup-apps' | 'core-isolation') => Promise<{ opened: boolean; pageId: string }>;
      getReleaseStatus: () => Promise<ReleaseStatus>;
      getBootTime?: () => Promise<string>;
      checkForUpdates: () => Promise<UpdateCheckResult>;
      downloadUpdate: (token: string) => Promise<UpdateDownloadResult>;
      launchUpdateInstaller: (token: string) => Promise<{ launched: boolean; version: string; fileName: string }>;
      getLocalRecommendations: () => Promise<LocalRecommendation[]>;
      getDriftReport: () => Promise<DriftReport>;
      setDriftBaseline: () => Promise<DriftReport>;
      listStartupItems: () => Promise<{ items: StartupManagementItem[]; errors: Array<{ component: string; message: string }> }>;
      disableStartupItem: (itemId: string) => Promise<{ success: boolean; entry: AuditJournalEntry; result?: unknown; error?: string }>;
      listManageableProcesses: () => Promise<{ items: ManageableProcess[]; errors: Array<{ component: string; message: string }> }>;
      enableProcessEcoQos: (processId: number, creationTime: string) => Promise<{ success: boolean; entry: AuditJournalEntry; result?: unknown; error?: string }>;
      listSafePolicies: () => Promise<{ items: SafeOsPolicy[]; errors: Array<{ component: string; message: string }> }>;
      enableConsumerFeaturesPolicy: () => Promise<PolicyMutationResult>;
      confirmConsumerFeaturesPolicy: (throttleToken: string) => Promise<PolicyMutationResult>;
      openExternalLink: (url: string) => Promise<{ opened: boolean }>;
      listTimingExperiments: () => Promise<{ items: TimingExperiment[]; errors: Array<{ component: string; message: string }> }>;
      executeTimingExperiment: (actionId: NonNullable<TimingExperiment['actionId']>) => Promise<{ success: boolean; entry: AuditJournalEntry; result?: unknown; error?: string }>;
      listGameSettingsGuides: () => Promise<GameSettingsGuide[]>;
      readDisplayInventory: () => Promise<ReportedDisplayInventory>;
      readBiosPlan: () => Promise<import('./types').BiosGuidancePlan>;
      scanInputDevices: () => Promise<import('./lib/inputDevices').InputInventory>;
      getInputDriverLifecycleStatus: (deviceDigest?: string) => Promise<import('./lib/inputDevices').InputDriverLifecycleStatus>;
      getBundledInputStatus: () => Promise<import('./lib/inputDevices').BundledInputStatus>;
      openBundledInputSetup: (deviceId: string) => Promise<{ status: 'OPENED'; changed: false }>;
      onBundledInputSetupClosed: (listener: () => void) => () => void;
      previewInputDriverInstall: (deviceDigest: string, requestedHz: number) => Promise<import('./lib/inputDevices').InputDriverLifecyclePreview>;
      previewInputDriverAdoption: (deviceDigest: string, requestedHz: number) => Promise<import('./lib/inputDevices').InputDriverLifecyclePreview>;
      previewInputDriverRepair: (deviceDigest: string) => Promise<import('./lib/inputDevices').InputDriverLifecyclePreview>;
      previewInputDriverUpgrade: () => Promise<import('./lib/inputDevices').InputDriverLifecyclePreview>;
      previewInputDriverDetach: (deviceDigest: string) => Promise<import('./lib/inputDevices').InputDriverLifecyclePreview>;
      previewInputDriverPackageRemoval: () => Promise<import('./lib/inputDevices').InputDriverLifecyclePreview>;
      applyInputDriverLifecycle: (token: string) => Promise<import('./lib/inputDevices').InputDriverLifecycleResult>;
      reconcileInputDriverLifecycle: (operationId: string) => Promise<import('./lib/inputDevices').InputDriverLifecycleStatus>;
      labelInputPort: (deviceId: string, label: string) => Promise<import('./lib/inputDevices').InputInventory>;
      previewInputPolling: (deviceId: string, rate: number, historyId?: string) => Promise<import('./lib/inputDevices').InputPreview>;
      previewInputIsolation: (deviceId: string) => Promise<import('./lib/inputDevices').InputPreview>;
      applyInputPolling: (token: string) => Promise<import('./lib/inputDevices').InputResult>;
      previewInputTier: (deviceId: string, historyId?: string) => Promise<import('./lib/inputDevices').InputTierPreview>;
      applyInputTier: (token: string) => Promise<import('./lib/inputDevices').InputTierResult>;
      testInputDevice: (deviceId: string) => Promise<import('./lib/inputDevices').InputTest>;
      cancelInputTest: () => Promise<{ canceled: boolean }>;
      reconcileInputChange: (historyId: string) => Promise<import('./lib/inputDevices').InputInventory>;
      reconcileInputTier: (historyId: string) => Promise<import('./lib/inputDevices').InputInventory>;
      listGameProfiles: () => Promise<import('./types').GameOptimizationProfile[]>;
      previewGameProfile: (profileId: string) => Promise<import('./types').GameOptimizationPreview>;
      applyGameProfile: (token: string) => Promise<import('./types').GameOptimizationResult>;
      discoverInstalledGames: () => Promise<InstalledGameDiscovery>;
      listGameConfigBackups: () => Promise<GameConfigBackup[]>;
      createGameConfigBackup: (gameId: string) => Promise<{ canceled: boolean; backup?: GameConfigBackup }>;
      previewGameConfigRestore: (backupId: string) => Promise<GameConfigRestorePreview>;
      applyGameConfigRestore: (token: string) => Promise<GameConfigRestoreResult>;
      getNetworkProbeInfo: () => Promise<NetworkProbeEndpoint[]>;
      listNetworkQualityHistory: () => Promise<NetworkQualityHistoryState>;
      previewNetworkQualityProbe: (mode: 'quick' | 'full') => Promise<NetworkProbeConsentPreview>;
      runNetworkQualityProbe: (token: string) => Promise<NetworkProbeResult>;
      getNetworkProbeProgress: () => Promise<NetworkProbeProgress | null>;
      cancelNetworkQualityProbe: () => Promise<{ canceled: boolean }>;
      executeMaintenance: (actionId: string) => Promise<{
        success: boolean;
        entry: AuditJournalEntry;
        result?: unknown;
        error?: string;
      }>;
      inspectMaintenanceCaches: () => Promise<import('./types').CacheCleanupInventory>;
      listPowerPlans: () => Promise<import('./types').PowerPlanInventory>;
      activatePowerPlan: (guid: string) => Promise<{ success: boolean; entry: AuditJournalEntry; result?: unknown; error?: string }>;
      listGpuPreferences: () => Promise<import('./types').GpuPreferenceItem[]>;
      chooseGpuPreferenceApp: () => Promise<{ canceled: boolean; item?: import('./types').GpuPreferenceItem }>;
      setGpuPreference: (targetId: string, preference: 0 | 1 | 2) => Promise<{ success: boolean; entry: AuditJournalEntry; result?: unknown; error?: string }>;
      listFullscreenOptimizations: () => Promise<import('./types').FullscreenOptimizationItem[]>;
      chooseFullscreenOptimizationsApp: () => Promise<{ canceled: boolean; item?: import('./types').FullscreenOptimizationItem }>;
      setFullscreenOptimizations: (targetId: string, disableOptimizations: boolean) => Promise<{ success: boolean; entry: AuditJournalEntry; result?: unknown; error?: string }>;
      readUserSettings: () => Promise<Partial<Record<'game-mode' | 'background-recording' | 'gpu-scheduling' | 'mpo' | 'global-timer-resolution' | 'mouse-acceleration' | 'ultimate-plan' | 'cpu-minimum-state' | 'block-background-apps' | 'exclude-driver-updates' | 'no-auto-restart' | 'windowed-games' | 'usb-selective-suspend', { enabled: boolean | null; manageable: boolean; detail?: string; unsupported?: string }>>>;
      setUserSetting: (settingId: 'game-mode' | 'background-recording' | 'gpu-scheduling' | 'mpo' | 'global-timer-resolution' | 'mouse-acceleration' | 'ultimate-plan' | 'cpu-minimum-state' | 'block-background-apps' | 'exclude-driver-updates' | 'no-auto-restart' | 'windowed-games' | 'usb-selective-suspend', enabled: boolean) => Promise<{ success: boolean; entry: AuditJournalEntry; result?: unknown; error?: string }>;
      readDisplayModes: () => Promise<import('./types').DisplayModeReport>;
      readWifiStatus: () => Promise<import('./types').WifiStatusReport>;
      getAuditHistory: () => Promise<AuditHistoryState>;
      retryAuditVerification: () => Promise<AuditHistoryState>;
      recoverCorruptAuditJournal: () => Promise<AuditJournalRecoveryResult>;
      getAuditExportPreview: () => Promise<AuditExportPreview>;
      exportAuditHistory: () => Promise<{ canceled: boolean; fileName?: string; entryCount?: number }>;
      getAuditDeletionPreview: (mode: AuditDeletionMode) => Promise<AuditDeletionPreview>;
      deleteAuditHistory: (token: string) => Promise<{ deletedCount: number; retainedCount: number; entries: AuditJournalEntry[] }>;
      listBenchmarkEvidence: () => Promise<BenchmarkEvidenceState>;
      getPresentMonInfo: () => Promise<PresentMonToolInfo>;
      listPresentMonTargets: () => Promise<{ scannedAt: string; items: PresentMonTarget[]; limitations: string }>;
      getPresentMonCaptureState: () => Promise<PresentMonCaptureState>;
      previewPresentMonCapture: (targetId: string, durationSeconds: 10 | 20 | 30, hardwareReadings?: boolean) => Promise<PresentMonCaptureConsentPreview>;
      readLiveHardware: (seconds?: 5 | 15 | 30) => Promise<import('./types').LiveHardwareReading>;
      startPresentMonCapture: (token: string) => Promise<PresentMonCaptureEntry>;
      stopPresentMonCapture: () => Promise<{ stopped: boolean; captureId?: string; reason?: string }>;
      prepareNativePresentMonImport: (captureIds: string[]) => Promise<BenchmarkImportPreview>;
      previewPresentMonCaptureDeletion: (captureId: string) => Promise<import('./types').PresentMonCaptureDeletionPreview>;
      deletePresentMonCapture: (token: string) => Promise<PresentMonCaptureState & { deleted: boolean; captureId: string; deletedFiles: Array<{ kind: string; fileName: string; bytes: number }> }>;
      previewBenchmarkImport: () => Promise<BenchmarkImportPreview>;
      preparePresentMonImport: (token: string, metadata: PresentMonImportMetadata) => Promise<BenchmarkImportPreview>;
      applyBenchmarkImport: (token: string) => Promise<BenchmarkEvidenceState>;
      previewBenchmarkDeletion: (experimentId: string) => Promise<{ token: string; experimentId: string; deletedCount: number; summary: Array<Record<string, unknown>> }>;
      deleteBenchmarkExperiment: (token: string) => Promise<BenchmarkEvidenceState & { deletedCount: number }>;
      rollbackAuditEntry: (entryId: string) => Promise<{ success: boolean; entry: AuditJournalEntry; result?: unknown; error?: string }>;
    };
  }
}

export {};
